district_to_rate = {
    'Деснянський': 25,
    'Солом\'янський': 60,
    'Дарницький': 40,
    'Голосіївський': 65,
    'Дніпровський': 35,
    'Оболонський': 55,
    'Подільський': 70,
    'Печерський': 95,
    'Святошинський': 37,
    'Шевченківський': 80,
}

input_lvs = [
    # Розмір квартири
    {
        'X': (1, 101, 1),  # Відносна площа квартири нормована
        'name': 'Apartment size',
        'terms': {
            'small': ('trapmf', 0, 0, 15, 25),
            'medium': ('trapmf', 18, 30, 50, 60),
            'large': ('trapmf', 55, 65, 70, 76),
            'very large': ('trapmf', 75, 90, 100, 100),
        }
    },
    # Преміальність району
    {
        'X': (1, 101, 1),  # Оцінка району
        'name': 'District level',
        'terms': {
            'below average': ('trapmf', 1, 1, 15, 40),
            'average': ('trapmf', 20, 40, 45, 60),
            'cool': ('trapmf', 30, 60, 80, 90),
            'very cool': ('trapmf', 75, 90, 100, 100),
        }
    },
    # Розмірність квартири (базується на кімнатності)
    {
        'X': (1, 7, 1),  # Кімнатність
        'name': 'Apartment scale',
        'terms': {
            # замінити значення
            'small': ('trapmf', 1, 1, 2, 2),
            'medium': ('trimf', 2, 2, 4),
            'large': ('trapmf', 2, 3, 4, 4),
            'very large': ('trapmf', 3, 4, 6, 6),
        }
    },
    # Час до метро
    {
        'X': (0, 61, 1),
        'name': 'Subway time',
        'terms': {
            'near': ('trapmf', 0, 0, 5, 15),
            'average': ('trapmf', 5, 10, 20, 25),
            'far away': ('trapmf', 20, 30, 60, 60),
        }
    },
    # Облаштованість квартири aбо стан ремонту
    {
        'X': (0, 101, 1),
        'name': 'Apartment state',
        'terms': {
            'empty': ('trapmf', 0, 0, 10, 20),
            'poor': ('trapmf', 10, 20, 35, 50),
            'average': ('trapmf', 30, 40, 60, 70),
            'comfort': ('trapmf', 50, 65, 80, 90),
            'rich': ('trapmf', 70, 85, 100, 100),
        }
    }
]

output_lv = {
    'X': (0, 101, 1),  # min(price) - max(price) Треба додати реальні ціни, а не шкалу від 0 до 100
    'name': 'Price',
    'terms': {
        'very low': ('trapmf', 0, 0, 5, 10),
        'low': ('trapmf', 0, 10, 25, 35),
        'below medium': ('trapmf', 20, 30, 40, 50),
        'medium': ('trapmf', 40, 45, 55, 60),
        'above medium': ('trapmf', 50, 60, 70, 80),
        'high': ('trapmf', 60, 70, 80, 90),
        'extremely high': ('trapmf', 75, 90, 100, 100),
    }
}
rule_base = [
    (('small', 'average', 'small', 'near', 'empty'), 'extremely high'),
    (('small', 'average', 'small', 'near', 'poor'), 'medium'),
    (('small', 'average', 'small', 'near', 'average'), 'medium'),
    (('small', 'average', 'small', 'near', 'comfort'), 'above medium'),
    (('small', 'average', 'small', 'near', 'rich'), 'low'),
    (('small', 'average', 'small', 'average', 'empty'), 'extremely high'),
    (('small', 'average', 'small', 'average', 'poor'), 'extremely high'),
    (('small', 'average', 'small', 'average', 'average'), 'high'),
    (('small', 'average', 'small', 'average', 'comfort'), 'very low'),
    (('small', 'average', 'small', 'average', 'rich'), 'below medium'),
    (('small', 'average', 'small', 'far away', 'empty'), 'low'),
    (('small', 'average', 'small', 'far away', 'poor'), 'medium'),
    (('small', 'average', 'small', 'far away', 'average'), 'very low'),
    (('small', 'average', 'small', 'far away', 'comfort'), 'above medium'),
    (('small', 'average', 'small', 'far away', 'rich'), 'above medium'),
    (('small', 'average', 'medium', 'near', 'empty'), 'below medium'),
    (('small', 'average', 'medium', 'near', 'poor'), 'high'),
    (('small', 'average', 'medium', 'near', 'average'), 'very low'),
    (('small', 'average', 'medium', 'near', 'comfort'), 'above medium'),
    (('small', 'average', 'medium', 'near', 'rich'), 'low'),
    (('small', 'average', 'medium', 'average', 'empty'), 'low'),
    (('small', 'average', 'medium', 'average', 'poor'), 'very low'),
    (('small', 'average', 'medium', 'average', 'average'), 'extremely high'),
    (('small', 'average', 'medium', 'average', 'comfort'), 'below medium'),
    (('small', 'average', 'medium', 'average', 'rich'), 'low'),
    (('small', 'average', 'medium', 'far away', 'empty'), 'medium'),
    (('small', 'average', 'medium', 'far away', 'poor'), 'extremely high'),
    (('small', 'average', 'medium', 'far away', 'average'), 'medium'),
    (('small', 'average', 'medium', 'far away', 'comfort'), 'below medium'),
    (('small', 'average', 'medium', 'far away', 'rich'), 'below medium'),
    (('small', 'average', 'large', 'near', 'empty'), 'low'),
    (('small', 'average', 'large', 'near', 'poor'), 'very low'),
    (('small', 'average', 'large', 'near', 'average'), 'extremely high'),
    (('small', 'average', 'large', 'near', 'comfort'), 'high'),
    (('small', 'average', 'large', 'near', 'rich'), 'below medium'),
    (('small', 'average', 'large', 'average', 'empty'), 'low'),
    (('small', 'average', 'large', 'average', 'poor'), 'high'),
    (('small', 'average', 'large', 'average', 'average'), 'below medium'),
    (('small', 'average', 'large', 'average', 'comfort'), 'low'),
    (('small', 'average', 'large', 'average', 'rich'), 'medium'),
    (('small', 'average', 'large', 'far away', 'empty'), 'low'),
    (('small', 'average', 'large', 'far away', 'poor'), 'low'),
    (('small', 'average', 'large', 'far away', 'average'), 'very low'),
    (('small', 'average', 'large', 'far away', 'comfort'), 'extremely high'),
    (('small', 'average', 'large', 'far away', 'rich'), 'below medium'),
    (('small', 'average', 'very large', 'near', 'empty'), 'extremely high'),
    (('small', 'average', 'very large', 'near', 'poor'), 'low'),
    (('small', 'average', 'very large', 'near', 'average'), 'low'),
    (('small', 'average', 'very large', 'near', 'comfort'), 'low'),
    (('small', 'average', 'very large', 'near', 'rich'), 'extremely high'),
    (('small', 'average', 'very large', 'average', 'empty'), 'very low'),
    (('small', 'average', 'very large', 'average', 'poor'), 'very low'),
    (('small', 'average', 'very large', 'average', 'average'), 'below medium'),
    (('small', 'average', 'very large', 'average', 'comfort'), 'low'),
    (('small', 'average', 'very large', 'average', 'rich'), 'above medium'),
    (('small', 'average', 'very large', 'far away', 'empty'), 'very low'),
    (('small', 'average', 'very large', 'far away', 'poor'), 'high'),
    (('small', 'average', 'very large', 'far away', 'average'), 'above medium'),
    (('small', 'average', 'very large', 'far away', 'comfort'), 'low'),
    (('small', 'average', 'very large', 'far away', 'rich'), 'high'),
    (('small', 'cool', 'small', 'near', 'empty'), 'below medium'),
    (('small', 'cool', 'small', 'near', 'poor'), 'very low'),
    (('small', 'cool', 'small', 'near', 'average'), 'very low'),
    (('small', 'cool', 'small', 'near', 'comfort'), 'low'),
    (('small', 'cool', 'small', 'near', 'rich'), 'low'),
    (('small', 'cool', 'small', 'average', 'empty'), 'very low'),
    (('small', 'cool', 'small', 'average', 'poor'), 'below medium'),
    (('small', 'cool', 'small', 'average', 'average'), 'very low'),
    (('small', 'cool', 'small', 'average', 'comfort'), 'medium'),
    (('small', 'cool', 'small', 'average', 'rich'), 'medium'),
    (('small', 'cool', 'small', 'far away', 'empty'), 'below medium'),
    (('small', 'cool', 'small', 'far away', 'poor'), 'very low'),
    (('small', 'cool', 'small', 'far away', 'average'), 'low'),
    (('small', 'cool', 'small', 'far away', 'comfort'), 'low'),
    (('small', 'cool', 'small', 'far away', 'rich'), 'medium'),
    (('small', 'cool', 'medium', 'near', 'empty'), 'high'),
    (('small', 'cool', 'medium', 'near', 'poor'), 'medium'),
    (('small', 'cool', 'medium', 'near', 'average'), 'medium'),
    (('small', 'cool', 'medium', 'near', 'comfort'), 'very low'),
    (('small', 'cool', 'medium', 'near', 'rich'), 'high'),
    (('small', 'cool', 'medium', 'average', 'empty'), 'low'),
    (('small', 'cool', 'medium', 'average', 'poor'), 'low'),
    (('small', 'cool', 'medium', 'average', 'average'), 'above medium'),
    (('small', 'cool', 'medium', 'average', 'comfort'), 'above medium'),
    (('small', 'cool', 'medium', 'average', 'rich'), 'extremely high'),
    (('small', 'cool', 'medium', 'far away', 'empty'), 'low'),
    (('small', 'cool', 'medium', 'far away', 'poor'), 'above medium'),
    (('small', 'cool', 'medium', 'far away', 'average'), 'low'),
    (('small', 'cool', 'medium', 'far away', 'comfort'), 'very low'),
    (('small', 'cool', 'medium', 'far away', 'rich'), 'medium'),
    (('small', 'cool', 'large', 'near', 'empty'), 'high'),
    (('small', 'cool', 'large', 'near', 'poor'), 'very low'),
    (('small', 'cool', 'large', 'near', 'average'), 'medium'),
    (('small', 'cool', 'large', 'near', 'comfort'), 'medium'),
    (('small', 'cool', 'large', 'near', 'rich'), 'medium'),
    (('small', 'cool', 'large', 'average', 'empty'), 'above medium'),
    (('small', 'cool', 'large', 'average', 'poor'), 'very low'),
    (('small', 'cool', 'large', 'average', 'average'), 'very low'),
    (('small', 'cool', 'large', 'average', 'comfort'), 'low'),
    (('small', 'cool', 'large', 'average', 'rich'), 'below medium'),
    (('small', 'cool', 'large', 'far away', 'empty'), 'high'),
    (('small', 'cool', 'large', 'far away', 'poor'), 'below medium'),
    (('small', 'cool', 'large', 'far away', 'average'), 'low'),
    (('small', 'cool', 'large', 'far away', 'comfort'), 'low'),
    (('small', 'cool', 'large', 'far away', 'rich'), 'extremely high'),
    (('small', 'cool', 'very large', 'near', 'empty'), 'very low'),
    (('small', 'cool', 'very large', 'near', 'poor'), 'above medium'),
    (('small', 'cool', 'very large', 'near', 'average'), 'extremely high'),
    (('small', 'cool', 'very large', 'near', 'comfort'), 'below medium'),
    (('small', 'cool', 'very large', 'near', 'rich'), 'high'),
    (('small', 'cool', 'very large', 'average', 'empty'), 'above medium'),
    (('small', 'cool', 'very large', 'average', 'poor'), 'low'),
    (('small', 'cool', 'very large', 'average', 'average'), 'medium'),
    (('small', 'cool', 'very large', 'average', 'comfort'), 'high'),
    (('small', 'cool', 'very large', 'average', 'rich'), 'very low'),
    (('small', 'cool', 'very large', 'far away', 'empty'), 'low'),
    (('small', 'cool', 'very large', 'far away', 'poor'), 'very low'),
    (('small', 'cool', 'very large', 'far away', 'average'), 'below medium'),
    (('small', 'cool', 'very large', 'far away', 'comfort'), 'high'),
    (('small', 'cool', 'very large', 'far away', 'rich'), 'medium'),
    (('small', 'very cool', 'small', 'near', 'empty'), 'low'),
    (('small', 'very cool', 'small', 'near', 'poor'), 'low'),
    (('small', 'very cool', 'small', 'near', 'average'), 'very low'),
    (('small', 'very cool', 'small', 'near', 'comfort'), 'medium'),
    (('small', 'very cool', 'small', 'near', 'rich'), 'high'),
    (('small', 'very cool', 'small', 'average', 'empty'), 'medium'),
    (('small', 'very cool', 'small', 'average', 'poor'), 'medium'),
    (('small', 'very cool', 'small', 'average', 'average'), 'below medium'),
    (('small', 'very cool', 'small', 'average', 'comfort'), 'low'),
    (('small', 'very cool', 'small', 'average', 'rich'), 'low'),
    (('small', 'very cool', 'small', 'far away', 'empty'), 'above medium'),
    (('small', 'very cool', 'small', 'far away', 'poor'), 'extremely high'),
    (('small', 'very cool', 'small', 'far away', 'average'), 'very low'),
    (('small', 'very cool', 'small', 'far away', 'comfort'), 'below medium'),
    (('small', 'very cool', 'small', 'far away', 'rich'), 'above medium'),
    (('small', 'very cool', 'medium', 'near', 'empty'), 'medium'),
    (('small', 'very cool', 'medium', 'near', 'poor'), 'low'),
    (('small', 'very cool', 'medium', 'near', 'average'), 'extremely high'),
    (('small', 'very cool', 'medium', 'near', 'comfort'), 'above medium'),
    (('small', 'very cool', 'medium', 'near', 'rich'), 'below medium'),
    (('small', 'very cool', 'medium', 'average', 'empty'), 'above medium'),
    (('small', 'very cool', 'medium', 'average', 'poor'), 'high'),
    (('small', 'very cool', 'medium', 'average', 'average'), 'low'),
    (('small', 'very cool', 'medium', 'average', 'comfort'), 'medium'),
    (('small', 'very cool', 'medium', 'average', 'rich'), 'high'),
    (('small', 'very cool', 'medium', 'far away', 'empty'), 'below medium'),
    (('small', 'very cool', 'medium', 'far away', 'poor'), 'above medium'),
    (('small', 'very cool', 'medium', 'far away', 'average'), 'high'),
    (('small', 'very cool', 'medium', 'far away', 'comfort'), 'below medium'),
    (('small', 'very cool', 'medium', 'far away', 'rich'), 'medium'),
    (('small', 'very cool', 'large', 'near', 'empty'), 'medium'),
    (('small', 'very cool', 'large', 'near', 'poor'), 'above medium'),
    (('small', 'very cool', 'large', 'near', 'average'), 'low'),
    (('small', 'very cool', 'large', 'near', 'comfort'), 'low'),
    (('small', 'very cool', 'large', 'near', 'rich'), 'very low'),
    (('small', 'very cool', 'large', 'average', 'empty'), 'high'),
    (('small', 'very cool', 'large', 'average', 'poor'), 'low'),
    (('small', 'very cool', 'large', 'average', 'average'), 'medium'),
    (('small', 'very cool', 'large', 'average', 'comfort'), 'high'),
    (('small', 'very cool', 'large', 'average', 'rich'), 'medium'),
    (('small', 'very cool', 'large', 'far away', 'empty'), 'very low'),
    (('small', 'very cool', 'large', 'far away', 'poor'), 'extremely high'),
    (('small', 'very cool', 'large', 'far away', 'average'), 'medium'),
    (('small', 'very cool', 'large', 'far away', 'comfort'), 'medium'),
    (('small', 'very cool', 'large', 'far away', 'rich'), 'extremely high'),
    (('small', 'very cool', 'very large', 'near', 'empty'), 'medium'),
    (('small', 'very cool', 'very large', 'near', 'poor'), 'medium'),
    (('small', 'very cool', 'very large', 'near', 'average'), 'medium'),
    (('small', 'very cool', 'very large', 'near', 'comfort'), 'below medium'),
    (('small', 'very cool', 'very large', 'near', 'rich'), 'extremely high'),
    (('small', 'very cool', 'very large', 'average', 'empty'), 'above medium'),
    (('small', 'very cool', 'very large', 'average', 'poor'), 'low'),
    (('small', 'very cool', 'very large', 'average', 'average'), 'very low'),
    (('small', 'very cool', 'very large', 'average', 'comfort'), 'low'),
    (('small', 'very cool', 'very large', 'average', 'rich'), 'high'),
    (('small', 'very cool', 'very large', 'far away', 'empty'), 'low'),
    (('small', 'very cool', 'very large', 'far away', 'poor'), 'extremely high'),
    (('small', 'very cool', 'very large', 'far away', 'average'), 'above medium'),
    (('small', 'very cool', 'very large', 'far away', 'comfort'), 'low'),
    (('small', 'very cool', 'very large', 'far away', 'rich'), 'very low'),
    (('medium', 'average', 'small', 'near', 'empty'), 'above medium'),
    (('medium', 'average', 'small', 'near', 'poor'), 'high'),
    (('medium', 'average', 'small', 'near', 'average'), 'medium'),
    (('medium', 'average', 'small', 'near', 'comfort'), 'above medium'),
    (('medium', 'average', 'small', 'near', 'rich'), 'high'),
    (('medium', 'average', 'small', 'average', 'empty'), 'very low'),
    (('medium', 'average', 'small', 'average', 'poor'), 'low'),
    (('medium', 'average', 'small', 'average', 'average'), 'below medium'),
    (('medium', 'average', 'small', 'average', 'comfort'), 'low'),
    (('medium', 'average', 'small', 'average', 'rich'), 'very low'),
    (('medium', 'average', 'small', 'far away', 'empty'), 'below medium'),
    (('medium', 'average', 'small', 'far away', 'poor'), 'low'),
    (('medium', 'average', 'small', 'far away', 'average'), 'low'),
    (('medium', 'average', 'small', 'far away', 'comfort'), 'low'),
    (('medium', 'average', 'small', 'far away', 'rich'), 'medium'),
    (('medium', 'average', 'medium', 'near', 'empty'), 'very low'),
    (('medium', 'average', 'medium', 'near', 'poor'), 'medium'),
    (('medium', 'average', 'medium', 'near', 'average'), 'low'),
    (('medium', 'average', 'medium', 'near', 'comfort'), 'medium'),
    (('medium', 'average', 'medium', 'near', 'rich'), 'very low'),
    (('medium', 'average', 'medium', 'average', 'empty'), 'low'),
    (('medium', 'average', 'medium', 'average', 'poor'), 'medium'),
    (('medium', 'average', 'medium', 'average', 'average'), 'below medium'),
    (('medium', 'average', 'medium', 'average', 'comfort'), 'very low'),
    (('medium', 'average', 'medium', 'average', 'rich'), 'low'),
    (('medium', 'average', 'medium', 'far away', 'empty'), 'low'),
    (('medium', 'average', 'medium', 'far away', 'poor'), 'very low'),
    (('medium', 'average', 'medium', 'far away', 'average'), 'low'),
    (('medium', 'average', 'medium', 'far away', 'comfort'), 'low'),
    (('medium', 'average', 'medium', 'far away', 'rich'), 'low'),
    (('medium', 'average', 'large', 'near', 'empty'), 'low'),
    (('medium', 'average', 'large', 'near', 'poor'), 'high'),
    (('medium', 'average', 'large', 'near', 'average'), 'low'),
    (('medium', 'average', 'large', 'near', 'comfort'), 'medium'),
    (('medium', 'average', 'large', 'near', 'rich'), 'medium'),
    (('medium', 'average', 'large', 'average', 'empty'), 'extremely high'),
    (('medium', 'average', 'large', 'average', 'poor'), 'extremely high'),
    (('medium', 'average', 'large', 'average', 'average'), 'extremely high'),
    (('medium', 'average', 'large', 'average', 'comfort'), 'above medium'),
    (('medium', 'average', 'large', 'average', 'rich'), 'low'),
    (('medium', 'average', 'large', 'far away', 'empty'), 'medium'),
    (('medium', 'average', 'large', 'far away', 'poor'), 'medium'),
    (('medium', 'average', 'large', 'far away', 'average'), 'extremely high'),
    (('medium', 'average', 'large', 'far away', 'comfort'), 'very low'),
    (('medium', 'average', 'large', 'far away', 'rich'), 'extremely high'),
    (('medium', 'average', 'very large', 'near', 'empty'), 'very low'),
    (('medium', 'average', 'very large', 'near', 'poor'), 'below medium'),
    (('medium', 'average', 'very large', 'near', 'average'), 'extremely high'),
    (('medium', 'average', 'very large', 'near', 'comfort'), 'medium'),
    (('medium', 'average', 'very large', 'near', 'rich'), 'low'),
    (('medium', 'average', 'very large', 'average', 'empty'), 'above medium'),
    (('medium', 'average', 'very large', 'average', 'poor'), 'medium'),
    (('medium', 'average', 'very large', 'average', 'average'), 'very low'),
    (('medium', 'average', 'very large', 'average', 'comfort'), 'low'),
    (('medium', 'average', 'very large', 'average', 'rich'), 'low'),
    (('medium', 'average', 'very large', 'far away', 'empty'), 'very low'),
    (('medium', 'average', 'very large', 'far away', 'poor'), 'high'),
    (('medium', 'average', 'very large', 'far away', 'average'), 'low'),
    (('medium', 'average', 'very large', 'far away', 'comfort'), 'low'),
    (('medium', 'average', 'very large', 'far away', 'rich'), 'above medium'),
    (('medium', 'cool', 'small', 'near', 'empty'), 'high'),
    (('medium', 'cool', 'small', 'near', 'poor'), 'below medium'),
    (('medium', 'cool', 'small', 'near', 'average'), 'low'),
    (('medium', 'cool', 'small', 'near', 'comfort'), 'above medium'),
    (('medium', 'cool', 'small', 'near', 'rich'), 'below medium'),
    (('medium', 'cool', 'small', 'average', 'empty'), 'above medium'),
    (('medium', 'cool', 'small', 'average', 'poor'), 'very low'),
    (('medium', 'cool', 'small', 'average', 'average'), 'low'),
    (('medium', 'cool', 'small', 'average', 'comfort'), 'very low'),
    (('medium', 'cool', 'small', 'average', 'rich'), 'extremely high'),
    (('medium', 'cool', 'small', 'far away', 'empty'), 'below medium'),
    (('medium', 'cool', 'small', 'far away', 'poor'), 'low'),
    (('medium', 'cool', 'small', 'far away', 'average'), 'very low'),
    (('medium', 'cool', 'small', 'far away', 'comfort'), 'very low'),
    (('medium', 'cool', 'small', 'far away', 'rich'), 'medium'),
    (('medium', 'cool', 'medium', 'near', 'empty'), 'low'),
    (('medium', 'cool', 'medium', 'near', 'poor'), 'above medium'),
    (('medium', 'cool', 'medium', 'near', 'average'), 'above medium'),
    (('medium', 'cool', 'medium', 'near', 'comfort'), 'above medium'),
    (('medium', 'cool', 'medium', 'near', 'rich'), 'high'),
    (('medium', 'cool', 'medium', 'average', 'empty'), 'low'),
    (('medium', 'cool', 'medium', 'average', 'poor'), 'high'),
    (('medium', 'cool', 'medium', 'average', 'average'), 'low'),
    (('medium', 'cool', 'medium', 'average', 'comfort'), 'medium'),
    (('medium', 'cool', 'medium', 'average', 'rich'), 'high'),
    (('medium', 'cool', 'medium', 'far away', 'empty'), 'low'),
    (('medium', 'cool', 'medium', 'far away', 'poor'), 'medium'),
    (('medium', 'cool', 'medium', 'far away', 'average'), 'below medium'),
    (('medium', 'cool', 'medium', 'far away', 'comfort'), 'extremely high'),
    (('medium', 'cool', 'medium', 'far away', 'rich'), 'low'),
    (('medium', 'cool', 'large', 'near', 'empty'), 'medium'),
    (('medium', 'cool', 'large', 'near', 'poor'), 'medium'),
    (('medium', 'cool', 'large', 'near', 'average'), 'medium'),
    (('medium', 'cool', 'large', 'near', 'comfort'), 'extremely high'),
    (('medium', 'cool', 'large', 'near', 'rich'), 'medium'),
    (('medium', 'cool', 'large', 'average', 'empty'), 'low'),
    (('medium', 'cool', 'large', 'average', 'poor'), 'low'),
    (('medium', 'cool', 'large', 'average', 'average'), 'medium'),
    (('medium', 'cool', 'large', 'average', 'comfort'), 'medium'),
    (('medium', 'cool', 'large', 'average', 'rich'), 'below medium'),
    (('medium', 'cool', 'large', 'far away', 'empty'), 'below medium'),
    (('medium', 'cool', 'large', 'far away', 'poor'), 'extremely high'),
    (('medium', 'cool', 'large', 'far away', 'average'), 'high'),
    (('medium', 'cool', 'large', 'far away', 'comfort'), 'low'),
    (('medium', 'cool', 'large', 'far away', 'rich'), 'below medium'),
    (('medium', 'cool', 'very large', 'near', 'empty'), 'very low'),
    (('medium', 'cool', 'very large', 'near', 'poor'), 'very low'),
    (('medium', 'cool', 'very large', 'near', 'average'), 'low'),
    (('medium', 'cool', 'very large', 'near', 'comfort'), 'extremely high'),
    (('medium', 'cool', 'very large', 'near', 'rich'), 'extremely high'),
    (('medium', 'cool', 'very large', 'average', 'empty'), 'medium'),
    (('medium', 'cool', 'very large', 'average', 'poor'), 'high'),
    (('medium', 'cool', 'very large', 'average', 'average'), 'above medium'),
    (('medium', 'cool', 'very large', 'average', 'comfort'), 'extremely high'),
    (('medium', 'cool', 'very large', 'average', 'rich'), 'above medium'),
    (('medium', 'cool', 'very large', 'far away', 'empty'), 'above medium'),
    (('medium', 'cool', 'very large', 'far away', 'poor'), 'very low'),
    (('medium', 'cool', 'very large', 'far away', 'average'), 'low'),
    (('medium', 'cool', 'very large', 'far away', 'comfort'), 'below medium'),
    (('medium', 'cool', 'very large', 'far away', 'rich'), 'high'),
    (('medium', 'very cool', 'small', 'near', 'empty'), 'extremely high'),
    (('medium', 'very cool', 'small', 'near', 'poor'), 'high'),
    (('medium', 'very cool', 'small', 'near', 'average'), 'medium'),
    (('medium', 'very cool', 'small', 'near', 'comfort'), 'low'),
    (('medium', 'very cool', 'small', 'near', 'rich'), 'medium'),
    (('medium', 'very cool', 'small', 'average', 'empty'), 'above medium'),
    (('medium', 'very cool', 'small', 'average', 'poor'), 'extremely high'),
    (('medium', 'very cool', 'small', 'average', 'average'), 'low'),
    (('medium', 'very cool', 'small', 'average', 'comfort'), 'very low'),
    (('medium', 'very cool', 'small', 'average', 'rich'), 'very low'),
    (('medium', 'very cool', 'small', 'far away', 'empty'), 'above medium'),
    (('medium', 'very cool', 'small', 'far away', 'poor'), 'low'),
    (('medium', 'very cool', 'small', 'far away', 'average'), 'below medium'),
    (('medium', 'very cool', 'small', 'far away', 'comfort'), 'high'),
    (('medium', 'very cool', 'small', 'far away', 'rich'), 'medium'),
    (('medium', 'very cool', 'medium', 'near', 'empty'), 'low'),
    (('medium', 'very cool', 'medium', 'near', 'poor'), 'very low'),
    (('medium', 'very cool', 'medium', 'near', 'average'), 'very low'),
    (('medium', 'very cool', 'medium', 'near', 'comfort'), 'very low'),
    (('medium', 'very cool', 'medium', 'near', 'rich'), 'very low'),
    (('medium', 'very cool', 'medium', 'average', 'empty'), 'very low'),
    (('medium', 'very cool', 'medium', 'average', 'poor'), 'medium'),
    (('medium', 'very cool', 'medium', 'average', 'average'), 'low'),
    (('medium', 'very cool', 'medium', 'average', 'comfort'), 'low'),
    (('medium', 'very cool', 'medium', 'average', 'rich'), 'low'),
    (('medium', 'very cool', 'medium', 'far away', 'empty'), 'very low'),
    (('medium', 'very cool', 'medium', 'far away', 'poor'), 'medium'),
    (('medium', 'very cool', 'medium', 'far away', 'average'), 'very low'),
    (('medium', 'very cool', 'medium', 'far away', 'comfort'), 'low'),
    (('medium', 'very cool', 'medium', 'far away', 'rich'), 'extremely high'),
    (('medium', 'very cool', 'large', 'near', 'empty'), 'extremely high'),
    (('medium', 'very cool', 'large', 'near', 'poor'), 'very low'),
    (('medium', 'very cool', 'large', 'near', 'average'), 'very low'),
    (('medium', 'very cool', 'large', 'near', 'comfort'), 'above medium'),
    (('medium', 'very cool', 'large', 'near', 'rich'), 'above medium'),
    (('medium', 'very cool', 'large', 'average', 'empty'), 'medium'),
    (('medium', 'very cool', 'large', 'average', 'poor'), 'high'),
    (('medium', 'very cool', 'large', 'average', 'average'), 'above medium'),
    (('medium', 'very cool', 'large', 'average', 'comfort'), 'low'),
    (('medium', 'very cool', 'large', 'average', 'rich'), 'medium'),
    (('medium', 'very cool', 'large', 'far away', 'empty'), 'low'),
    (('medium', 'very cool', 'large', 'far away', 'poor'), 'very low'),
    (('medium', 'very cool', 'large', 'far away', 'average'), 'medium'),
    (('medium', 'very cool', 'large', 'far away', 'comfort'), 'low'),
    (('medium', 'very cool', 'large', 'far away', 'rich'), 'above medium'),
    (('medium', 'very cool', 'very large', 'near', 'empty'), 'above medium'),
    (('medium', 'very cool', 'very large', 'near', 'poor'), 'below medium'),
    (('medium', 'very cool', 'very large', 'near', 'average'), 'very low'),
    (('medium', 'very cool', 'very large', 'near', 'comfort'), 'medium'),
    (('medium', 'very cool', 'very large', 'near', 'rich'), 'above medium'),
    (('medium', 'very cool', 'very large', 'average', 'empty'), 'high'),
    (('medium', 'very cool', 'very large', 'average', 'poor'), 'very low'),
    (('medium', 'very cool', 'very large', 'average', 'average'), 'low'),
    (('medium', 'very cool', 'very large', 'average', 'comfort'), 'extremely high'),
    (('medium', 'very cool', 'very large', 'average', 'rich'), 'very low'),
    (('medium', 'very cool', 'very large', 'far away', 'empty'), 'above medium'),
    (('medium', 'very cool', 'very large', 'far away', 'poor'), 'very low'),
    (('medium', 'very cool', 'very large', 'far away', 'average'), 'high'),
    (('medium', 'very cool', 'very large', 'far away', 'comfort'), 'very low'),
    (('medium', 'very cool', 'very large', 'far away', 'rich'), 'low'),
    (('large', 'average', 'small', 'near', 'empty'), 'medium'),
    (('large', 'average', 'small', 'near', 'poor'), 'low'),
    (('large', 'average', 'small', 'near', 'average'), 'medium'),
    (('large', 'average', 'small', 'near', 'comfort'), 'medium'),
    (('large', 'average', 'small', 'near', 'rich'), 'above medium'),
    (('large', 'average', 'small', 'average', 'empty'), 'above medium'),
    (('large', 'average', 'small', 'average', 'poor'), 'low'),
    (('large', 'average', 'small', 'average', 'average'), 'below medium'),
    (('large', 'average', 'small', 'average', 'comfort'), 'low'),
    (('large', 'average', 'small', 'average', 'rich'), 'above medium'),
    (('large', 'average', 'small', 'far away', 'empty'), 'extremely high'),
    (('large', 'average', 'small', 'far away', 'poor'), 'very low'),
    (('large', 'average', 'small', 'far away', 'average'), 'medium'),
    (('large', 'average', 'small', 'far away', 'comfort'), 'very low'),
    (('large', 'average', 'small', 'far away', 'rich'), 'below medium'),
    (('large', 'average', 'medium', 'near', 'empty'), 'very low'),
    (('large', 'average', 'medium', 'near', 'poor'), 'above medium'),
    (('large', 'average', 'medium', 'near', 'average'), 'low'),
    (('large', 'average', 'medium', 'near', 'comfort'), 'very low'),
    (('large', 'average', 'medium', 'near', 'rich'), 'very low'),
    (('large', 'average', 'medium', 'average', 'empty'), 'low'),
    (('large', 'average', 'medium', 'average', 'poor'), 'high'),
    (('large', 'average', 'medium', 'average', 'average'), 'very low'),
    (('large', 'average', 'medium', 'average', 'comfort'), 'low'),
    (('large', 'average', 'medium', 'average', 'rich'), 'medium'),
    (('large', 'average', 'medium', 'far away', 'empty'), 'below medium'),
    (('large', 'average', 'medium', 'far away', 'poor'), 'very low'),
    (('large', 'average', 'medium', 'far away', 'average'), 'very low'),
    (('large', 'average', 'medium', 'far away', 'comfort'), 'low'),
    (('large', 'average', 'medium', 'far away', 'rich'), 'very low'),
    (('large', 'average', 'large', 'near', 'empty'), 'high'),
    (('large', 'average', 'large', 'near', 'poor'), 'high'),
    (('large', 'average', 'large', 'near', 'average'), 'low'),
    (('large', 'average', 'large', 'near', 'comfort'), 'extremely high'),
    (('large', 'average', 'large', 'near', 'rich'), 'low'),
    (('large', 'average', 'large', 'average', 'empty'), 'medium'),
    (('large', 'average', 'large', 'average', 'poor'), 'low'),
    (('large', 'average', 'large', 'average', 'average'), 'above medium'),
    (('large', 'average', 'large', 'average', 'comfort'), 'high'),
    (('large', 'average', 'large', 'average', 'rich'), 'low'),
    (('large', 'average', 'large', 'far away', 'empty'), 'low'),
    (('large', 'average', 'large', 'far away', 'poor'), 'low'),
    (('large', 'average', 'large', 'far away', 'average'), 'low'),
    (('large', 'average', 'large', 'far away', 'comfort'), 'low'),
    (('large', 'average', 'large', 'far away', 'rich'), 'extremely high'),
    (('large', 'average', 'very large', 'near', 'empty'), 'low'),
    (('large', 'average', 'very large', 'near', 'poor'), 'below medium'),
    (('large', 'average', 'very large', 'near', 'average'), 'above medium'),
    (('large', 'average', 'very large', 'near', 'comfort'), 'high'),
    (('large', 'average', 'very large', 'near', 'rich'), 'low'),
    (('large', 'average', 'very large', 'average', 'empty'), 'below medium'),
    (('large', 'average', 'very large', 'average', 'poor'), 'below medium'),
    (('large', 'average', 'very large', 'average', 'average'), 'above medium'),
    (('large', 'average', 'very large', 'average', 'comfort'), 'high'),
    (('large', 'average', 'very large', 'average', 'rich'), 'very low'),
    (('large', 'average', 'very large', 'far away', 'empty'), 'high'),
    (('large', 'average', 'very large', 'far away', 'poor'), 'high'),
    (('large', 'average', 'very large', 'far away', 'average'), 'very low'),
    (('large', 'average', 'very large', 'far away', 'comfort'), 'medium'),
    (('large', 'average', 'very large', 'far away', 'rich'), 'low'),
    (('large', 'cool', 'small', 'near', 'empty'), 'low'),
    (('large', 'cool', 'small', 'near', 'poor'), 'below medium'),
    (('large', 'cool', 'small', 'near', 'average'), 'low'),
    (('large', 'cool', 'small', 'near', 'comfort'), 'below medium'),
    (('large', 'cool', 'small', 'near', 'rich'), 'medium'),
    (('large', 'cool', 'small', 'average', 'empty'), 'medium'),
    (('large', 'cool', 'small', 'average', 'poor'), 'medium'),
    (('large', 'cool', 'small', 'average', 'average'), 'very low'),
    (('large', 'cool', 'small', 'average', 'comfort'), 'below medium'),
    (('large', 'cool', 'small', 'average', 'rich'), 'medium'),
    (('large', 'cool', 'small', 'far away', 'empty'), 'low'),
    (('large', 'cool', 'small', 'far away', 'poor'), 'low'),
    (('large', 'cool', 'small', 'far away', 'average'), 'low'),
    (('large', 'cool', 'small', 'far away', 'comfort'), 'above medium'),
    (('large', 'cool', 'small', 'far away', 'rich'), 'low'),
    (('large', 'cool', 'medium', 'near', 'empty'), 'medium'),
    (('large', 'cool', 'medium', 'near', 'poor'), 'above medium'),
    (('large', 'cool', 'medium', 'near', 'average'), 'low'),
    (('large', 'cool', 'medium', 'near', 'comfort'), 'very low'),
    (('large', 'cool', 'medium', 'near', 'rich'), 'very low'),
    (('large', 'cool', 'medium', 'average', 'empty'), 'medium'),
    (('large', 'cool', 'medium', 'average', 'poor'), 'low'),
    (('large', 'cool', 'medium', 'average', 'average'), 'very low'),
    (('large', 'cool', 'medium', 'average', 'comfort'), 'low'),
    (('large', 'cool', 'medium', 'average', 'rich'), 'medium'),
    (('large', 'cool', 'medium', 'far away', 'empty'), 'low'),
    (('large', 'cool', 'medium', 'far away', 'poor'), 'low'),
    (('large', 'cool', 'medium', 'far away', 'average'), 'below medium'),
    (('large', 'cool', 'medium', 'far away', 'comfort'), 'low'),
    (('large', 'cool', 'medium', 'far away', 'rich'), 'low'),
    (('large', 'cool', 'large', 'near', 'empty'), 'medium'),
    (('large', 'cool', 'large', 'near', 'poor'), 'medium'),
    (('large', 'cool', 'large', 'near', 'average'), 'very low'),
    (('large', 'cool', 'large', 'near', 'comfort'), 'extremely high'),
    (('large', 'cool', 'large', 'near', 'rich'), 'high'),
    (('large', 'cool', 'large', 'average', 'empty'), 'above medium'),
    (('large', 'cool', 'large', 'average', 'poor'), 'low'),
    (('large', 'cool', 'large', 'average', 'average'), 'below medium'),
    (('large', 'cool', 'large', 'average', 'comfort'), 'high'),
    (('large', 'cool', 'large', 'average', 'rich'), 'below medium'),
    (('large', 'cool', 'large', 'far away', 'empty'), 'very low'),
    (('large', 'cool', 'large', 'far away', 'poor'), 'low'),
    (('large', 'cool', 'large', 'far away', 'average'), 'low'),
    (('large', 'cool', 'large', 'far away', 'comfort'), 'low'),
    (('large', 'cool', 'large', 'far away', 'rich'), 'below medium'),
    (('large', 'cool', 'very large', 'near', 'empty'), 'above medium'),
    (('large', 'cool', 'very large', 'near', 'poor'), 'low'),
    (('large', 'cool', 'very large', 'near', 'average'), 'medium'),
    (('large', 'cool', 'very large', 'near', 'comfort'), 'very low'),
    (('large', 'cool', 'very large', 'near', 'rich'), 'low'),
    (('large', 'cool', 'very large', 'average', 'empty'), 'below medium'),
    (('large', 'cool', 'very large', 'average', 'poor'), 'low'),
    (('large', 'cool', 'very large', 'average', 'average'), 'below medium'),
    (('large', 'cool', 'very large', 'average', 'comfort'), 'high'),
    (('large', 'cool', 'very large', 'average', 'rich'), 'low'),
    (('large', 'cool', 'very large', 'far away', 'empty'), 'very low'),
    (('large', 'cool', 'very large', 'far away', 'poor'), 'high'),
    (('large', 'cool', 'very large', 'far away', 'average'), 'low'),
    (('large', 'cool', 'very large', 'far away', 'comfort'), 'below medium'),
    (('large', 'cool', 'very large', 'far away', 'rich'), 'above medium'),
    (('large', 'very cool', 'small', 'near', 'empty'), 'low'),
    (('large', 'very cool', 'small', 'near', 'poor'), 'below medium'),
    (('large', 'very cool', 'small', 'near', 'average'), 'very low'),
    (('large', 'very cool', 'small', 'near', 'comfort'), 'medium'),
    (('large', 'very cool', 'small', 'near', 'rich'), 'very low'),
    (('large', 'very cool', 'small', 'average', 'empty'), 'extremely high'),
    (('large', 'very cool', 'small', 'average', 'poor'), 'medium'),
    (('large', 'very cool', 'small', 'average', 'average'), 'low'),
    (('large', 'very cool', 'small', 'average', 'comfort'), 'low'),
    (('large', 'very cool', 'small', 'average', 'rich'), 'extremely high'),
    (('large', 'very cool', 'small', 'far away', 'empty'), 'low'),
    (('large', 'very cool', 'small', 'far away', 'poor'), 'above medium'),
    (('large', 'very cool', 'small', 'far away', 'average'), 'high'),
    (('large', 'very cool', 'small', 'far away', 'comfort'), 'very low'),
    (('large', 'very cool', 'small', 'far away', 'rich'), 'low'),
    (('large', 'very cool', 'medium', 'near', 'empty'), 'high'),
    (('large', 'very cool', 'medium', 'near', 'poor'), 'low'),
    (('large', 'very cool', 'medium', 'near', 'average'), 'above medium'),
    (('large', 'very cool', 'medium', 'near', 'comfort'), 'very low'),
    (('large', 'very cool', 'medium', 'near', 'rich'), 'very low'),
    (('large', 'very cool', 'medium', 'average', 'empty'), 'very low'),
    (('large', 'very cool', 'medium', 'average', 'poor'), 'below medium'),
    (('large', 'very cool', 'medium', 'average', 'average'), 'above medium'),
    (('large', 'very cool', 'medium', 'average', 'comfort'), 'medium'),
    (('large', 'very cool', 'medium', 'average', 'rich'), 'low'),
    (('large', 'very cool', 'medium', 'far away', 'empty'), 'above medium'),
    (('large', 'very cool', 'medium', 'far away', 'poor'), 'very low'),
    (('large', 'very cool', 'medium', 'far away', 'average'), 'very low'),
    (('large', 'very cool', 'medium', 'far away', 'comfort'), 'low'),
    (('large', 'very cool', 'medium', 'far away', 'rich'), 'low'),
    (('large', 'very cool', 'large', 'near', 'empty'), 'high'),
    (('large', 'very cool', 'large', 'near', 'poor'), 'extremely high'),
    (('large', 'very cool', 'large', 'near', 'average'), 'below medium'),
    (('large', 'very cool', 'large', 'near', 'comfort'), 'low'),
    (('large', 'very cool', 'large', 'near', 'rich'), 'low'),
    (('large', 'very cool', 'large', 'average', 'empty'), 'high'),
    (('large', 'very cool', 'large', 'average', 'poor'), 'below medium'),
    (('large', 'very cool', 'large', 'average', 'average'), 'low'),
    (('large', 'very cool', 'large', 'average', 'comfort'), 'above medium'),
    (('large', 'very cool', 'large', 'average', 'rich'), 'extremely high'),
    (('large', 'very cool', 'large', 'far away', 'empty'), 'extremely high'),
    (('large', 'very cool', 'large', 'far away', 'poor'), 'very low'),
    (('large', 'very cool', 'large', 'far away', 'average'), 'low'),
    (('large', 'very cool', 'large', 'far away', 'comfort'), 'below medium'),
    (('large', 'very cool', 'large', 'far away', 'rich'), 'high'),
    (('large', 'very cool', 'very large', 'near', 'empty'), 'very low'),
    (('large', 'very cool', 'very large', 'near', 'poor'), 'above medium'),
    (('large', 'very cool', 'very large', 'near', 'average'), 'low'),
    (('large', 'very cool', 'very large', 'near', 'comfort'), 'extremely high'),
    (('large', 'very cool', 'very large', 'near', 'rich'), 'low'),
    (('large', 'very cool', 'very large', 'average', 'empty'), 'extremely high'),
    (('large', 'very cool', 'very large', 'average', 'poor'), 'extremely high'),
    (('large', 'very cool', 'very large', 'average', 'average'), 'low'),
    (('large', 'very cool', 'very large', 'average', 'comfort'), 'below medium'),
    (('large', 'very cool', 'very large', 'average', 'rich'), 'below medium'),
    (('large', 'very cool', 'very large', 'far away', 'empty'), 'high'),
    (('large', 'very cool', 'very large', 'far away', 'poor'), 'medium'),
    (('large', 'very cool', 'very large', 'far away', 'average'), 'above medium'),
    (('large', 'very cool', 'very large', 'far away', 'comfort'), 'medium'),
    (('large', 'very cool', 'very large', 'far away', 'rich'), 'below medium'),
    (('very large', 'average', 'small', 'near', 'empty'), 'above medium'),
    (('very large', 'average', 'small', 'near', 'poor'), 'medium'),
    (('very large', 'average', 'small', 'near', 'average'), 'extremely high'),
    (('very large', 'average', 'small', 'near', 'comfort'), 'low'),
    (('very large', 'average', 'small', 'near', 'rich'), 'low'),
    (('very large', 'average', 'small', 'average', 'empty'), 'medium'),
    (('very large', 'average', 'small', 'average', 'poor'), 'below medium'),
    (('very large', 'average', 'small', 'average', 'average'), 'below medium'),
    (('very large', 'average', 'small', 'average', 'comfort'), 'extremely high'),
    (('very large', 'average', 'small', 'average', 'rich'), 'extremely high'),
    (('very large', 'average', 'small', 'far away', 'empty'), 'high'),
    (('very large', 'average', 'small', 'far away', 'poor'), 'low'),
    (('very large', 'average', 'small', 'far away', 'average'), 'below medium'),
    (('very large', 'average', 'small', 'far away', 'comfort'), 'very low'),
    (('very large', 'average', 'small', 'far away', 'rich'), 'high'),
    (('very large', 'average', 'medium', 'near', 'empty'), 'below medium'),
    (('very large', 'average', 'medium', 'near', 'poor'), 'very low'),
    (('very large', 'average', 'medium', 'near', 'average'), 'below medium'),
    (('very large', 'average', 'medium', 'near', 'comfort'), 'below medium'),
    (('very large', 'average', 'medium', 'near', 'rich'), 'medium'),
    (('very large', 'average', 'medium', 'average', 'empty'), 'medium'),
    (('very large', 'average', 'medium', 'average', 'poor'), 'very low'),
    (('very large', 'average', 'medium', 'average', 'average'), 'very low'),
    (('very large', 'average', 'medium', 'average', 'comfort'), 'low'),
    (('very large', 'average', 'medium', 'average', 'rich'), 'extremely high'),
    (('very large', 'average', 'medium', 'far away', 'empty'), 'below medium'),
    (('very large', 'average', 'medium', 'far away', 'poor'), 'medium'),
    (('very large', 'average', 'medium', 'far away', 'average'), 'low'),
    (('very large', 'average', 'medium', 'far away', 'comfort'), 'medium'),
    (('very large', 'average', 'medium', 'far away', 'rich'), 'above medium'),
    (('very large', 'average', 'large', 'near', 'empty'), 'low'),
    (('very large', 'average', 'large', 'near', 'poor'), 'below medium'),
    (('very large', 'average', 'large', 'near', 'average'), 'below medium'),
    (('very large', 'average', 'large', 'near', 'comfort'), 'low'),
    (('very large', 'average', 'large', 'near', 'rich'), 'low'),
    (('very large', 'average', 'large', 'average', 'empty'), 'low'),
    (('very large', 'average', 'large', 'average', 'poor'), 'extremely high'),
    (('very large', 'average', 'large', 'average', 'average'), 'low'),
    (('very large', 'average', 'large', 'average', 'comfort'), 'extremely high'),
    (('very large', 'average', 'large', 'average', 'rich'), 'low'),
    (('very large', 'average', 'large', 'far away', 'empty'), 'low'),
    (('very large', 'average', 'large', 'far away', 'poor'), 'very low'),
    (('very large', 'average', 'large', 'far away', 'average'), 'low'),
    (('very large', 'average', 'large', 'far away', 'comfort'), 'very low'),
    (('very large', 'average', 'large', 'far away', 'rich'), 'low'),
    (('very large', 'average', 'very large', 'near', 'empty'), 'very low'),
    (('very large', 'average', 'very large', 'near', 'poor'), 'above medium'),
    (('very large', 'average', 'very large', 'near', 'average'), 'high'),
    (('very large', 'average', 'very large', 'near', 'comfort'), 'below medium'),
    (('very large', 'average', 'very large', 'near', 'rich'), 'low'),
    (('very large', 'average', 'very large', 'average', 'empty'), 'low'),
    (('very large', 'average', 'very large', 'average', 'poor'), 'low'),
    (('very large', 'average', 'very large', 'average', 'average'), 'low'),
    (('very large', 'average', 'very large', 'average', 'comfort'), 'low'),
    (('very large', 'average', 'very large', 'average', 'rich'), 'low'),
    (('very large', 'average', 'very large', 'far away', 'empty'), 'above medium'),
    (('very large', 'average', 'very large', 'far away', 'poor'), 'extremely high'),
    (('very large', 'average', 'very large', 'far away', 'average'), 'low'),
    (('very large', 'average', 'very large', 'far away', 'comfort'), 'very low'),
    (('very large', 'average', 'very large', 'far away', 'rich'), 'very low'),
    (('very large', 'cool', 'small', 'near', 'empty'), 'high'),
    (('very large', 'cool', 'small', 'near', 'poor'), 'very low'),
    (('very large', 'cool', 'small', 'near', 'average'), 'above medium'),
    (('very large', 'cool', 'small', 'near', 'comfort'), 'low'),
    (('very large', 'cool', 'small', 'near', 'rich'), 'high'),
    (('very large', 'cool', 'small', 'average', 'empty'), 'low'),
    (('very large', 'cool', 'small', 'average', 'poor'), 'high'),
    (('very large', 'cool', 'small', 'average', 'average'), 'below medium'),
    (('very large', 'cool', 'small', 'average', 'comfort'), 'low'),
    (('very large', 'cool', 'small', 'average', 'rich'), 'extremely high'),
    (('very large', 'cool', 'small', 'far away', 'empty'), 'high'),
    (('very large', 'cool', 'small', 'far away', 'poor'), 'below medium'),
    (('very large', 'cool', 'small', 'far away', 'average'), 'low'),
    (('very large', 'cool', 'small', 'far away', 'comfort'), 'high'),
    (('very large', 'cool', 'small', 'far away', 'rich'), 'very low'),
    (('very large', 'cool', 'medium', 'near', 'empty'), 'above medium'),
    (('very large', 'cool', 'medium', 'near', 'poor'), 'below medium'),
    (('very large', 'cool', 'medium', 'near', 'average'), 'very low'),
    (('very large', 'cool', 'medium', 'near', 'comfort'), 'above medium'),
    (('very large', 'cool', 'medium', 'near', 'rich'), 'above medium'),
    (('very large', 'cool', 'medium', 'average', 'empty'), 'above medium'),
    (('very large', 'cool', 'medium', 'average', 'poor'), 'high'),
    (('very large', 'cool', 'medium', 'average', 'average'), 'below medium'),
    (('very large', 'cool', 'medium', 'average', 'comfort'), 'high'),
    (('very large', 'cool', 'medium', 'average', 'rich'), 'above medium'),
    (('very large', 'cool', 'medium', 'far away', 'empty'), 'below medium'),
    (('very large', 'cool', 'medium', 'far away', 'poor'), 'extremely high'),
    (('very large', 'cool', 'medium', 'far away', 'average'), 'medium'),
    (('very large', 'cool', 'medium', 'far away', 'comfort'), 'above medium'),
    (('very large', 'cool', 'medium', 'far away', 'rich'), 'low'),
    (('very large', 'cool', 'large', 'near', 'empty'), 'below medium'),
    (('very large', 'cool', 'large', 'near', 'poor'), 'very low'),
    (('very large', 'cool', 'large', 'near', 'average'), 'below medium'),
    (('very large', 'cool', 'large', 'near', 'comfort'), 'low'),
    (('very large', 'cool', 'large', 'near', 'rich'), 'below medium'),
    (('very large', 'cool', 'large', 'average', 'empty'), 'low'),
    (('very large', 'cool', 'large', 'average', 'poor'), 'below medium'),
    (('very large', 'cool', 'large', 'average', 'average'), 'low'),
    (('very large', 'cool', 'large', 'average', 'comfort'), 'high'),
    (('very large', 'cool', 'large', 'average', 'rich'), 'low'),
    (('very large', 'cool', 'large', 'far away', 'empty'), 'very low'),
    (('very large', 'cool', 'large', 'far away', 'poor'), 'very low'),
    (('very large', 'cool', 'large', 'far away', 'average'), 'below medium'),
    (('very large', 'cool', 'large', 'far away', 'comfort'), 'low'),
    (('very large', 'cool', 'large', 'far away', 'rich'), 'medium'),
    (('very large', 'cool', 'very large', 'near', 'empty'), 'low'),
    (('very large', 'cool', 'very large', 'near', 'poor'), 'very low'),
    (('very large', 'cool', 'very large', 'near', 'average'), 'high'),
    (('very large', 'cool', 'very large', 'near', 'comfort'), 'below medium'),
    (('very large', 'cool', 'very large', 'near', 'rich'), 'high'),
    (('very large', 'cool', 'very large', 'average', 'empty'), 'below medium'),
    (('very large', 'cool', 'very large', 'average', 'poor'), 'above medium'),
    (('very large', 'cool', 'very large', 'average', 'average'), 'medium'),
    (('very large', 'cool', 'very large', 'average', 'comfort'), 'high'),
    (('very large', 'cool', 'very large', 'average', 'rich'), 'below medium'),
    (('very large', 'cool', 'very large', 'far away', 'empty'), 'below medium'),
    (('very large', 'cool', 'very large', 'far away', 'poor'), 'high'),
    (('very large', 'cool', 'very large', 'far away', 'average'), 'very low'),
    (('very large', 'cool', 'very large', 'far away', 'comfort'), 'very low'),
    (('very large', 'cool', 'very large', 'far away', 'rich'), 'medium'),
    (('very large', 'very cool', 'small', 'near', 'empty'), 'extremely high'),
    (('very large', 'very cool', 'small', 'near', 'poor'), 'extremely high'),
    (('very large', 'very cool', 'small', 'near', 'average'), 'very low'),
    (('very large', 'very cool', 'small', 'near', 'comfort'), 'low'),
    (('very large', 'very cool', 'small', 'near', 'rich'), 'above medium'),
    (('very large', 'very cool', 'small', 'average', 'empty'), 'high'),
    (('very large', 'very cool', 'small', 'average', 'poor'), 'low'),
    (('very large', 'very cool', 'small', 'average', 'average'), 'above medium'),
    (('very large', 'very cool', 'small', 'average', 'comfort'), 'low'),
    (('very large', 'very cool', 'small', 'average', 'rich'), 'low'),
    (('very large', 'very cool', 'small', 'far away', 'empty'), 'below medium'),
    (('very large', 'very cool', 'small', 'far away', 'poor'), 'extremely high'),
    (('very large', 'very cool', 'small', 'far away', 'average'), 'low'),
    (('very large', 'very cool', 'small', 'far away', 'comfort'), 'medium'),
    (('very large', 'very cool', 'small', 'far away', 'rich'), 'extremely high'),
    (('very large', 'very cool', 'medium', 'near', 'empty'), 'medium'),
    (('very large', 'very cool', 'medium', 'near', 'poor'), 'below medium'),
    (('very large', 'very cool', 'medium', 'near', 'average'), 'high'),
    (('very large', 'very cool', 'medium', 'near', 'comfort'), 'medium'),
    (('very large', 'very cool', 'medium', 'near', 'rich'), 'extremely high'),
    (('very large', 'very cool', 'medium', 'average', 'empty'), 'extremely high'),
    (('very large', 'very cool', 'medium', 'average', 'poor'), 'low'),
    (('very large', 'very cool', 'medium', 'average', 'average'), 'extremely high'),
    (('very large', 'very cool', 'medium', 'average', 'comfort'), 'very low'),
    (('very large', 'very cool', 'medium', 'average', 'rich'), 'above medium'),
    (('very large', 'very cool', 'medium', 'far away', 'empty'), 'low'),
    (('very large', 'very cool', 'medium', 'far away', 'poor'), 'very low'),
    (('very large', 'very cool', 'medium', 'far away', 'average'), 'extremely high'),
    (('very large', 'very cool', 'medium', 'far away', 'comfort'), 'low'),
    (('very large', 'very cool', 'medium', 'far away', 'rich'), 'below medium'),
    (('very large', 'very cool', 'large', 'near', 'empty'), 'very low'),
    (('very large', 'very cool', 'large', 'near', 'poor'), 'low'),
    (('very large', 'very cool', 'large', 'near', 'average'), 'very low'),
    (('very large', 'very cool', 'large', 'near', 'comfort'), 'low'),
    (('very large', 'very cool', 'large', 'near', 'rich'), 'very low'),
    (('very large', 'very cool', 'large', 'average', 'empty'), 'high'),
    (('very large', 'very cool', 'large', 'average', 'poor'), 'extremely high'),
    (('very large', 'very cool', 'large', 'average', 'average'), 'below medium'),
    (('very large', 'very cool', 'large', 'average', 'comfort'), 'medium'),
    (('very large', 'very cool', 'large', 'average', 'rich'), 'extremely high'),
    (('very large', 'very cool', 'large', 'far away', 'empty'), 'high'),
    (('very large', 'very cool', 'large', 'far away', 'poor'), 'low'),
    (('very large', 'very cool', 'large', 'far away', 'average'), 'very low'),
    (('very large', 'very cool', 'large', 'far away', 'comfort'), 'very low'),
    (('very large', 'very cool', 'large', 'far away', 'rich'), 'above medium'),
    (('very large', 'very cool', 'very large', 'near', 'empty'), 'above medium'),
    (('very large', 'very cool', 'very large', 'near', 'poor'), 'above medium'),
    (('very large', 'very cool', 'very large', 'near', 'average'), 'low'),
    (('very large', 'very cool', 'very large', 'near', 'comfort'), 'above medium'),
    (('very large', 'very cool', 'very large', 'near', 'rich'), 'high'),
    (('very large', 'very cool', 'very large', 'average', 'empty'), 'high'),
    (('very large', 'very cool', 'very large', 'average', 'poor'), 'low'),
    (('very large', 'very cool', 'very large', 'average', 'average'), 'very low'),
    (('very large', 'very cool', 'very large', 'average', 'comfort'), 'low'),
    (('very large', 'very cool', 'very large', 'average', 'rich'), 'low'),
    (('very large', 'very cool', 'very large', 'far away', 'empty'), 'above medium'),
    (('very large', 'very cool', 'very large', 'far away', 'poor'), 'very low'),
    (('very large', 'very cool', 'very large', 'far away', 'average'), 'high'),
    (('very large', 'very cool', 'very large', 'far away', 'comfort'), 'low'),
    (('very large', 'very cool', 'very large', 'far away', 'rich'), 'very low')
]
