conditions = [
        ('small', 'average', 'small', 'near', 'empty'),
        ('small', 'average', 'small', 'near', 'poor'),
        ('small', 'average', 'small', 'near', 'average'),
        ('small', 'average', 'small', 'near', 'comfort'),
        ('small', 'average', 'small', 'near', 'rich'),
        ('small', 'average', 'small', 'average', 'empty'),
        ('small', 'average', 'small', 'average', 'poor'),
        ('small', 'average', 'small', 'average', 'average'),
        ('small', 'average', 'small', 'average', 'comfort'),
        ('small', 'average', 'small', 'average', 'rich'),
        ('small', 'average', 'small', 'far away', 'empty'),
        ('small', 'average', 'small', 'far away', 'poor'),
        ('small', 'average', 'small', 'far away', 'average'),
        ('small', 'average', 'small', 'far away', 'comfort'),
        ('small', 'average', 'small', 'far away', 'rich'),
        ('small', 'average', 'medium', 'near', 'empty'),
        ('small', 'average', 'medium', 'near', 'poor'),
        ('small', 'average', 'medium', 'near', 'average'),
        ('small', 'average', 'medium', 'near', 'comfort'),
        ('small', 'average', 'medium', 'near', 'rich'),
        ('small', 'average', 'medium', 'average', 'empty'),
        ('small', 'average', 'medium', 'average', 'poor'),
        ('small', 'average', 'medium', 'average', 'average'),
        ('small', 'average', 'medium', 'average', 'comfort'),
        ('small', 'average', 'medium', 'average', 'rich'),
        ('small', 'average', 'medium', 'far away', 'empty'),
        ('small', 'average', 'medium', 'far away', 'poor'),
        ('small', 'average', 'medium', 'far away', 'average'),
        ('small', 'average', 'medium', 'far away', 'comfort'),
        ('small', 'average', 'medium', 'far away', 'rich'),
        ('small', 'average', 'large', 'near', 'empty'),
        ('small', 'average', 'large', 'near', 'poor'),
        ('small', 'average', 'large', 'near', 'average'),
        ('small', 'average', 'large', 'near', 'comfort'),
        ('small', 'average', 'large', 'near', 'rich'),
        ('small', 'average', 'large', 'average', 'empty'),
        ('small', 'average', 'large', 'average', 'poor'),
        ('small', 'average', 'large', 'average', 'average'),
        ('small', 'average', 'large', 'average', 'comfort'),
        ('small', 'average', 'large', 'average', 'rich'),
        ('small', 'average', 'large', 'far away', 'empty'),
        ('small', 'average', 'large', 'far away', 'poor'),
        ('small', 'average', 'large', 'far away', 'average'),
        ('small', 'average', 'large', 'far away', 'comfort'),
        ('small', 'average', 'large', 'far away', 'rich'),
        ('small', 'average', 'very large', 'near', 'empty'),
        ('small', 'average', 'very large', 'near', 'poor'),
        ('small', 'average', 'very large', 'near', 'average'),
        ('small', 'average', 'very large', 'near', 'comfort'),
        ('small', 'average', 'very large', 'near', 'rich'),
        ('small', 'average', 'very large', 'average', 'empty'),
        ('small', 'average', 'very large', 'average', 'poor'),
        ('small', 'average', 'very large', 'average', 'average'),
        ('small', 'average', 'very large', 'average', 'comfort'),
        ('small', 'average', 'very large', 'average', 'rich'),
        ('small', 'average', 'very large', 'far away', 'empty'),
        ('small', 'average', 'very large', 'far away', 'poor'),
        ('small', 'average', 'very large', 'far away', 'average'),
        ('small', 'average', 'very large', 'far away', 'comfort'),
        ('small', 'average', 'very large', 'far away', 'rich'),
        ('small', 'cool', 'small', 'near', 'empty'),
        ('small', 'cool', 'small', 'near', 'poor'),
        ('small', 'cool', 'small', 'near', 'average'),
        ('small', 'cool', 'small', 'near', 'comfort'),
        ('small', 'cool', 'small', 'near', 'rich'),
        ('small', 'cool', 'small', 'average', 'empty'),
        ('small', 'cool', 'small', 'average', 'poor'),
        ('small', 'cool', 'small', 'average', 'average'),
        ('small', 'cool', 'small', 'average', 'comfort'),
        ('small', 'cool', 'small', 'average', 'rich'),
        ('small', 'cool', 'small', 'far away', 'empty'),
        ('small', 'cool', 'small', 'far away', 'poor'),
        ('small', 'cool', 'small', 'far away', 'average'),
        ('small', 'cool', 'small', 'far away', 'comfort'),
        ('small', 'cool', 'small', 'far away', 'rich'),
        ('small', 'cool', 'medium', 'near', 'empty'),
        ('small', 'cool', 'medium', 'near', 'poor'),
        ('small', 'cool', 'medium', 'near', 'average'),
        ('small', 'cool', 'medium', 'near', 'comfort'),
        ('small', 'cool', 'medium', 'near', 'rich'),
        ('small', 'cool', 'medium', 'average', 'empty'),
        ('small', 'cool', 'medium', 'average', 'poor'),
        ('small', 'cool', 'medium', 'average', 'average'),
        ('small', 'cool', 'medium', 'average', 'comfort'),
        ('small', 'cool', 'medium', 'average', 'rich'),
        ('small', 'cool', 'medium', 'far away', 'empty'),
        ('small', 'cool', 'medium', 'far away', 'poor'),
        ('small', 'cool', 'medium', 'far away', 'average'),
        ('small', 'cool', 'medium', 'far away', 'comfort'),
        ('small', 'cool', 'medium', 'far away', 'rich'),
        ('small', 'cool', 'large', 'near', 'empty'),
        ('small', 'cool', 'large', 'near', 'poor'),
        ('small', 'cool', 'large', 'near', 'average'),
        ('small', 'cool', 'large', 'near', 'comfort'),
        ('small', 'cool', 'large', 'near', 'rich'),
        ('small', 'cool', 'large', 'average', 'empty'),
        ('small', 'cool', 'large', 'average', 'poor'),
        ('small', 'cool', 'large', 'average', 'average'),
        ('small', 'cool', 'large', 'average', 'comfort'),
        ('small', 'cool', 'large', 'average', 'rich'),
        ('small', 'cool', 'large', 'far away', 'empty'),
        ('small', 'cool', 'large', 'far away', 'poor'),
        ('small', 'cool', 'large', 'far away', 'average'),
        ('small', 'cool', 'large', 'far away', 'comfort'),
        ('small', 'cool', 'large', 'far away', 'rich'),
        ('small', 'cool', 'very large', 'near', 'empty'),
        ('small', 'cool', 'very large', 'near', 'poor'),
        ('small', 'cool', 'very large', 'near', 'average'),
        ('small', 'cool', 'very large', 'near', 'comfort'),
        ('small', 'cool', 'very large', 'near', 'rich'),
        ('small', 'cool', 'very large', 'average', 'empty'),
        ('small', 'cool', 'very large', 'average', 'poor'),
        ('small', 'cool', 'very large', 'average', 'average'),
        ('small', 'cool', 'very large', 'average', 'comfort'),
        ('small', 'cool', 'very large', 'average', 'rich'),
        ('small', 'cool', 'very large', 'far away', 'empty'),
        ('small', 'cool', 'very large', 'far away', 'poor'),
        ('small', 'cool', 'very large', 'far away', 'average'),
        ('small', 'cool', 'very large', 'far away', 'comfort'),
        ('small', 'cool', 'very large', 'far away', 'rich'),
        ('small', 'very cool', 'small', 'near', 'empty'),
        ('small', 'very cool', 'small', 'near', 'poor'),
        ('small', 'very cool', 'small', 'near', 'average'),
        ('small', 'very cool', 'small', 'near', 'comfort'),
        ('small', 'very cool', 'small', 'near', 'rich'),
        ('small', 'very cool', 'small', 'average', 'empty'),
        ('small', 'very cool', 'small', 'average', 'poor'),
        ('small', 'very cool', 'small', 'average', 'average'),
        ('small', 'very cool', 'small', 'average', 'comfort'),
        ('small', 'very cool', 'small', 'average', 'rich'),
        ('small', 'very cool', 'small', 'far away', 'empty'),
        ('small', 'very cool', 'small', 'far away', 'poor'),
        ('small', 'very cool', 'small', 'far away', 'average'),
        ('small', 'very cool', 'small', 'far away', 'comfort'),
        ('small', 'very cool', 'small', 'far away', 'rich'),
        ('small', 'very cool', 'medium', 'near', 'empty'),
        ('small', 'very cool', 'medium', 'near', 'poor'),
        ('small', 'very cool', 'medium', 'near', 'average'),
        ('small', 'very cool', 'medium', 'near', 'comfort'),
        ('small', 'very cool', 'medium', 'near', 'rich'),
        ('small', 'very cool', 'medium', 'average', 'empty'),
        ('small', 'very cool', 'medium', 'average', 'poor'),
        ('small', 'very cool', 'medium', 'average', 'average'),
        ('small', 'very cool', 'medium', 'average', 'comfort'),
        ('small', 'very cool', 'medium', 'average', 'rich'),
        ('small', 'very cool', 'medium', 'far away', 'empty'),
        ('small', 'very cool', 'medium', 'far away', 'poor'),
        ('small', 'very cool', 'medium', 'far away', 'average'),
        ('small', 'very cool', 'medium', 'far away', 'comfort'),
        ('small', 'very cool', 'medium', 'far away', 'rich'),
        ('small', 'very cool', 'large', 'near', 'empty'),
        ('small', 'very cool', 'large', 'near', 'poor'),
        ('small', 'very cool', 'large', 'near', 'average'),
        ('small', 'very cool', 'large', 'near', 'comfort'),
        ('small', 'very cool', 'large', 'near', 'rich'),
        ('small', 'very cool', 'large', 'average', 'empty'),
        ('small', 'very cool', 'large', 'average', 'poor'),
        ('small', 'very cool', 'large', 'average', 'average'),
        ('small', 'very cool', 'large', 'average', 'comfort'),
        ('small', 'very cool', 'large', 'average', 'rich'),
        ('small', 'very cool', 'large', 'far away', 'empty'),
        ('small', 'very cool', 'large', 'far away', 'poor'),
        ('small', 'very cool', 'large', 'far away', 'average'),
        ('small', 'very cool', 'large', 'far away', 'comfort'),
        ('small', 'very cool', 'large', 'far away', 'rich'),
        ('small', 'very cool', 'very large', 'near', 'empty'),
        ('small', 'very cool', 'very large', 'near', 'poor'),
        ('small', 'very cool', 'very large', 'near', 'average'),
        ('small', 'very cool', 'very large', 'near', 'comfort'),
        ('small', 'very cool', 'very large', 'near', 'rich'),
        ('small', 'very cool', 'very large', 'average', 'empty'),
        ('small', 'very cool', 'very large', 'average', 'poor'),
        ('small', 'very cool', 'very large', 'average', 'average'),
        ('small', 'very cool', 'very large', 'average', 'comfort'),
        ('small', 'very cool', 'very large', 'average', 'rich'),
        ('small', 'very cool', 'very large', 'far away', 'empty'),
        ('small', 'very cool', 'very large', 'far away', 'poor'),
        ('small', 'very cool', 'very large', 'far away', 'average'),
        ('small', 'very cool', 'very large', 'far away', 'comfort'),
        ('small', 'very cool', 'very large', 'far away', 'rich'),
        ('medium', 'average', 'small', 'near', 'empty'),
        ('medium', 'average', 'small', 'near', 'poor'),
        ('medium', 'average', 'small', 'near', 'average'),
        ('medium', 'average', 'small', 'near', 'comfort'),
        ('medium', 'average', 'small', 'near', 'rich'),
        ('medium', 'average', 'small', 'average', 'empty'),
        ('medium', 'average', 'small', 'average', 'poor'),
        ('medium', 'average', 'small', 'average', 'average'),
        ('medium', 'average', 'small', 'average', 'comfort'),
        ('medium', 'average', 'small', 'average', 'rich'),
        ('medium', 'average', 'small', 'far away', 'empty'),
        ('medium', 'average', 'small', 'far away', 'poor'),
        ('medium', 'average', 'small', 'far away', 'average'),
        ('medium', 'average', 'small', 'far away', 'comfort'),
        ('medium', 'average', 'small', 'far away', 'rich'),
        ('medium', 'average', 'medium', 'near', 'empty'),
        ('medium', 'average', 'medium', 'near', 'poor'),
        ('medium', 'average', 'medium', 'near', 'average'),
        ('medium', 'average', 'medium', 'near', 'comfort'),
        ('medium', 'average', 'medium', 'near', 'rich'),
        ('medium', 'average', 'medium', 'average', 'empty'),
        ('medium', 'average', 'medium', 'average', 'poor'),
        ('medium', 'average', 'medium', 'average', 'average'),
        ('medium', 'average', 'medium', 'average', 'comfort'),
        ('medium', 'average', 'medium', 'average', 'rich'),
        ('medium', 'average', 'medium', 'far away', 'empty'),
        ('medium', 'average', 'medium', 'far away', 'poor'),
        ('medium', 'average', 'medium', 'far away', 'average'),
        ('medium', 'average', 'medium', 'far away', 'comfort'),
        ('medium', 'average', 'medium', 'far away', 'rich'),
        ('medium', 'average', 'large', 'near', 'empty'),
        ('medium', 'average', 'large', 'near', 'poor'),
        ('medium', 'average', 'large', 'near', 'average'),
        ('medium', 'average', 'large', 'near', 'comfort'),
        ('medium', 'average', 'large', 'near', 'rich'),
        ('medium', 'average', 'large', 'average', 'empty'),
        ('medium', 'average', 'large', 'average', 'poor'),
        ('medium', 'average', 'large', 'average', 'average'),
        ('medium', 'average', 'large', 'average', 'comfort'),
        ('medium', 'average', 'large', 'average', 'rich'),
        ('medium', 'average', 'large', 'far away', 'empty'),
        ('medium', 'average', 'large', 'far away', 'poor'),
        ('medium', 'average', 'large', 'far away', 'average'),
        ('medium', 'average', 'large', 'far away', 'comfort'),
        ('medium', 'average', 'large', 'far away', 'rich'),
        ('medium', 'average', 'very large', 'near', 'empty'),
        ('medium', 'average', 'very large', 'near', 'poor'),
        ('medium', 'average', 'very large', 'near', 'average'),
        ('medium', 'average', 'very large', 'near', 'comfort'),
        ('medium', 'average', 'very large', 'near', 'rich'),
        ('medium', 'average', 'very large', 'average', 'empty'),
        ('medium', 'average', 'very large', 'average', 'poor'),
        ('medium', 'average', 'very large', 'average', 'average'),
        ('medium', 'average', 'very large', 'average', 'comfort'),
        ('medium', 'average', 'very large', 'average', 'rich'),
        ('medium', 'average', 'very large', 'far away', 'empty'),
        ('medium', 'average', 'very large', 'far away', 'poor'),
        ('medium', 'average', 'very large', 'far away', 'average'),
        ('medium', 'average', 'very large', 'far away', 'comfort'),
        ('medium', 'average', 'very large', 'far away', 'rich'),
        ('medium', 'cool', 'small', 'near', 'empty'),
        ('medium', 'cool', 'small', 'near', 'poor'),
        ('medium', 'cool', 'small', 'near', 'average'),
        ('medium', 'cool', 'small', 'near', 'comfort'),
        ('medium', 'cool', 'small', 'near', 'rich'),
        ('medium', 'cool', 'small', 'average', 'empty'),
        ('medium', 'cool', 'small', 'average', 'poor'),
        ('medium', 'cool', 'small', 'average', 'average'),
        ('medium', 'cool', 'small', 'average', 'comfort'),
        ('medium', 'cool', 'small', 'average', 'rich'),
        ('medium', 'cool', 'small', 'far away', 'empty'),
        ('medium', 'cool', 'small', 'far away', 'poor'),
        ('medium', 'cool', 'small', 'far away', 'average'),
        ('medium', 'cool', 'small', 'far away', 'comfort'),
        ('medium', 'cool', 'small', 'far away', 'rich'),
        ('medium', 'cool', 'medium', 'near', 'empty'),
        ('medium', 'cool', 'medium', 'near', 'poor'),
        ('medium', 'cool', 'medium', 'near', 'average'),
        ('medium', 'cool', 'medium', 'near', 'comfort'),
        ('medium', 'cool', 'medium', 'near', 'rich'),
        ('medium', 'cool', 'medium', 'average', 'empty'),
        ('medium', 'cool', 'medium', 'average', 'poor'),
        ('medium', 'cool', 'medium', 'average', 'average'),
        ('medium', 'cool', 'medium', 'average', 'comfort'),
        ('medium', 'cool', 'medium', 'average', 'rich'),
        ('medium', 'cool', 'medium', 'far away', 'empty'),
        ('medium', 'cool', 'medium', 'far away', 'poor'),
        ('medium', 'cool', 'medium', 'far away', 'average'),
        ('medium', 'cool', 'medium', 'far away', 'comfort'),
        ('medium', 'cool', 'medium', 'far away', 'rich'),
        ('medium', 'cool', 'large', 'near', 'empty'),
        ('medium', 'cool', 'large', 'near', 'poor'),
        ('medium', 'cool', 'large', 'near', 'average'),
        ('medium', 'cool', 'large', 'near', 'comfort'),
        ('medium', 'cool', 'large', 'near', 'rich'),
        ('medium', 'cool', 'large', 'average', 'empty'),
        ('medium', 'cool', 'large', 'average', 'poor'),
        ('medium', 'cool', 'large', 'average', 'average'),
        ('medium', 'cool', 'large', 'average', 'comfort'),
        ('medium', 'cool', 'large', 'average', 'rich'),
        ('medium', 'cool', 'large', 'far away', 'empty'),
        ('medium', 'cool', 'large', 'far away', 'poor'),
        ('medium', 'cool', 'large', 'far away', 'average'),
        ('medium', 'cool', 'large', 'far away', 'comfort'),
        ('medium', 'cool', 'large', 'far away', 'rich'),
        ('medium', 'cool', 'very large', 'near', 'empty'),
        ('medium', 'cool', 'very large', 'near', 'poor'),
        ('medium', 'cool', 'very large', 'near', 'average'),
        ('medium', 'cool', 'very large', 'near', 'comfort'),
        ('medium', 'cool', 'very large', 'near', 'rich'),
        ('medium', 'cool', 'very large', 'average', 'empty'),
        ('medium', 'cool', 'very large', 'average', 'poor'),
        ('medium', 'cool', 'very large', 'average', 'average'),
        ('medium', 'cool', 'very large', 'average', 'comfort'),
        ('medium', 'cool', 'very large', 'average', 'rich'),
        ('medium', 'cool', 'very large', 'far away', 'empty'),
        ('medium', 'cool', 'very large', 'far away', 'poor'),
        ('medium', 'cool', 'very large', 'far away', 'average'),
        ('medium', 'cool', 'very large', 'far away', 'comfort'),
        ('medium', 'cool', 'very large', 'far away', 'rich'),
        ('medium', 'very cool', 'small', 'near', 'empty'),
        ('medium', 'very cool', 'small', 'near', 'poor'),
        ('medium', 'very cool', 'small', 'near', 'average'),
        ('medium', 'very cool', 'small', 'near', 'comfort'),
        ('medium', 'very cool', 'small', 'near', 'rich'),
        ('medium', 'very cool', 'small', 'average', 'empty'),
        ('medium', 'very cool', 'small', 'average', 'poor'),
        ('medium', 'very cool', 'small', 'average', 'average'),
        ('medium', 'very cool', 'small', 'average', 'comfort'),
        ('medium', 'very cool', 'small', 'average', 'rich'),
        ('medium', 'very cool', 'small', 'far away', 'empty'),
        ('medium', 'very cool', 'small', 'far away', 'poor'),
        ('medium', 'very cool', 'small', 'far away', 'average'),
        ('medium', 'very cool', 'small', 'far away', 'comfort'),
        ('medium', 'very cool', 'small', 'far away', 'rich'),
        ('medium', 'very cool', 'medium', 'near', 'empty'),
        ('medium', 'very cool', 'medium', 'near', 'poor'),
        ('medium', 'very cool', 'medium', 'near', 'average'),
        ('medium', 'very cool', 'medium', 'near', 'comfort'),
        ('medium', 'very cool', 'medium', 'near', 'rich'),
        ('medium', 'very cool', 'medium', 'average', 'empty'),
        ('medium', 'very cool', 'medium', 'average', 'poor'),
        ('medium', 'very cool', 'medium', 'average', 'average'),
        ('medium', 'very cool', 'medium', 'average', 'comfort'),
        ('medium', 'very cool', 'medium', 'average', 'rich'),
        ('medium', 'very cool', 'medium', 'far away', 'empty'),
        ('medium', 'very cool', 'medium', 'far away', 'poor'),
        ('medium', 'very cool', 'medium', 'far away', 'average'),
        ('medium', 'very cool', 'medium', 'far away', 'comfort'),
        ('medium', 'very cool', 'medium', 'far away', 'rich'),
        ('medium', 'very cool', 'large', 'near', 'empty'),
        ('medium', 'very cool', 'large', 'near', 'poor'),
        ('medium', 'very cool', 'large', 'near', 'average'),
        ('medium', 'very cool', 'large', 'near', 'comfort'),
        ('medium', 'very cool', 'large', 'near', 'rich'),
        ('medium', 'very cool', 'large', 'average', 'empty'),
        ('medium', 'very cool', 'large', 'average', 'poor'),
        ('medium', 'very cool', 'large', 'average', 'average'),
        ('medium', 'very cool', 'large', 'average', 'comfort'),
        ('medium', 'very cool', 'large', 'average', 'rich'),
        ('medium', 'very cool', 'large', 'far away', 'empty'),
        ('medium', 'very cool', 'large', 'far away', 'poor'),
        ('medium', 'very cool', 'large', 'far away', 'average'),
        ('medium', 'very cool', 'large', 'far away', 'comfort'),
        ('medium', 'very cool', 'large', 'far away', 'rich'),
        ('medium', 'very cool', 'very large', 'near', 'empty'),
        ('medium', 'very cool', 'very large', 'near', 'poor'),
        ('medium', 'very cool', 'very large', 'near', 'average'),
        ('medium', 'very cool', 'very large', 'near', 'comfort'),
        ('medium', 'very cool', 'very large', 'near', 'rich'),
        ('medium', 'very cool', 'very large', 'average', 'empty'),
        ('medium', 'very cool', 'very large', 'average', 'poor'),
        ('medium', 'very cool', 'very large', 'average', 'average'),
        ('medium', 'very cool', 'very large', 'average', 'comfort'),
        ('medium', 'very cool', 'very large', 'average', 'rich'),
        ('medium', 'very cool', 'very large', 'far away', 'empty'),
        ('medium', 'very cool', 'very large', 'far away', 'poor'),
        ('medium', 'very cool', 'very large', 'far away', 'average'),
        ('medium', 'very cool', 'very large', 'far away', 'comfort'),
        ('medium', 'very cool', 'very large', 'far away', 'rich'),
        ('large', 'average', 'small', 'near', 'empty'),
        ('large', 'average', 'small', 'near', 'poor'),
        ('large', 'average', 'small', 'near', 'average'),
        ('large', 'average', 'small', 'near', 'comfort'),
        ('large', 'average', 'small', 'near', 'rich'),
        ('large', 'average', 'small', 'average', 'empty'),
        ('large', 'average', 'small', 'average', 'poor'),
        ('large', 'average', 'small', 'average', 'average'),
        ('large', 'average', 'small', 'average', 'comfort'),
        ('large', 'average', 'small', 'average', 'rich'),
        ('large', 'average', 'small', 'far away', 'empty'),
        ('large', 'average', 'small', 'far away', 'poor'),
        ('large', 'average', 'small', 'far away', 'average'),
        ('large', 'average', 'small', 'far away', 'comfort'),
        ('large', 'average', 'small', 'far away', 'rich'),
        ('large', 'average', 'medium', 'near', 'empty'),
        ('large', 'average', 'medium', 'near', 'poor'),
        ('large', 'average', 'medium', 'near', 'average'),
        ('large', 'average', 'medium', 'near', 'comfort'),
        ('large', 'average', 'medium', 'near', 'rich'),
        ('large', 'average', 'medium', 'average', 'empty'),
        ('large', 'average', 'medium', 'average', 'poor'),
        ('large', 'average', 'medium', 'average', 'average'),
        ('large', 'average', 'medium', 'average', 'comfort'),
        ('large', 'average', 'medium', 'average', 'rich'),
        ('large', 'average', 'medium', 'far away', 'empty'),
        ('large', 'average', 'medium', 'far away', 'poor'),
        ('large', 'average', 'medium', 'far away', 'average'),
        ('large', 'average', 'medium', 'far away', 'comfort'),
        ('large', 'average', 'medium', 'far away', 'rich'),
        ('large', 'average', 'large', 'near', 'empty'),
        ('large', 'average', 'large', 'near', 'poor'),
        ('large', 'average', 'large', 'near', 'average'),
        ('large', 'average', 'large', 'near', 'comfort'),
        ('large', 'average', 'large', 'near', 'rich'),
        ('large', 'average', 'large', 'average', 'empty'),
        ('large', 'average', 'large', 'average', 'poor'),
        ('large', 'average', 'large', 'average', 'average'),
        ('large', 'average', 'large', 'average', 'comfort'),
        ('large', 'average', 'large', 'average', 'rich'),
        ('large', 'average', 'large', 'far away', 'empty'),
        ('large', 'average', 'large', 'far away', 'poor'),
        ('large', 'average', 'large', 'far away', 'average'),
        ('large', 'average', 'large', 'far away', 'comfort'),
        ('large', 'average', 'large', 'far away', 'rich'),
        ('large', 'average', 'very large', 'near', 'empty'),
        ('large', 'average', 'very large', 'near', 'poor'),
        ('large', 'average', 'very large', 'near', 'average'),
        ('large', 'average', 'very large', 'near', 'comfort'),
        ('large', 'average', 'very large', 'near', 'rich'),
        ('large', 'average', 'very large', 'average', 'empty'),
        ('large', 'average', 'very large', 'average', 'poor'),
        ('large', 'average', 'very large', 'average', 'average'),
        ('large', 'average', 'very large', 'average', 'comfort'),
        ('large', 'average', 'very large', 'average', 'rich'),
        ('large', 'average', 'very large', 'far away', 'empty'),
        ('large', 'average', 'very large', 'far away', 'poor'),
        ('large', 'average', 'very large', 'far away', 'average'),
        ('large', 'average', 'very large', 'far away', 'comfort'),
        ('large', 'average', 'very large', 'far away', 'rich'),
        ('large', 'cool', 'small', 'near', 'empty'),
        ('large', 'cool', 'small', 'near', 'poor'),
        ('large', 'cool', 'small', 'near', 'average'),
        ('large', 'cool', 'small', 'near', 'comfort'),
        ('large', 'cool', 'small', 'near', 'rich'),
        ('large', 'cool', 'small', 'average', 'empty'),
        ('large', 'cool', 'small', 'average', 'poor'),
        ('large', 'cool', 'small', 'average', 'average'),
        ('large', 'cool', 'small', 'average', 'comfort'),
        ('large', 'cool', 'small', 'average', 'rich'),
        ('large', 'cool', 'small', 'far away', 'empty'),
        ('large', 'cool', 'small', 'far away', 'poor'),
        ('large', 'cool', 'small', 'far away', 'average'),
        ('large', 'cool', 'small', 'far away', 'comfort'),
        ('large', 'cool', 'small', 'far away', 'rich'),
        ('large', 'cool', 'medium', 'near', 'empty'),
        ('large', 'cool', 'medium', 'near', 'poor'),
        ('large', 'cool', 'medium', 'near', 'average'),
        ('large', 'cool', 'medium', 'near', 'comfort'),
        ('large', 'cool', 'medium', 'near', 'rich'),
        ('large', 'cool', 'medium', 'average', 'empty'),
        ('large', 'cool', 'medium', 'average', 'poor'),
        ('large', 'cool', 'medium', 'average', 'average'),
        ('large', 'cool', 'medium', 'average', 'comfort'),
        ('large', 'cool', 'medium', 'average', 'rich'),
        ('large', 'cool', 'medium', 'far away', 'empty'),
        ('large', 'cool', 'medium', 'far away', 'poor'),
        ('large', 'cool', 'medium', 'far away', 'average'),
        ('large', 'cool', 'medium', 'far away', 'comfort'),
        ('large', 'cool', 'medium', 'far away', 'rich'),
        ('large', 'cool', 'large', 'near', 'empty'),
        ('large', 'cool', 'large', 'near', 'poor'),
        ('large', 'cool', 'large', 'near', 'average'),
        ('large', 'cool', 'large', 'near', 'comfort'),
        ('large', 'cool', 'large', 'near', 'rich'),
        ('large', 'cool', 'large', 'average', 'empty'),
        ('large', 'cool', 'large', 'average', 'poor'),
        ('large', 'cool', 'large', 'average', 'average'),
        ('large', 'cool', 'large', 'average', 'comfort'),
        ('large', 'cool', 'large', 'average', 'rich'),
        ('large', 'cool', 'large', 'far away', 'empty'),
        ('large', 'cool', 'large', 'far away', 'poor'),
        ('large', 'cool', 'large', 'far away', 'average'),
        ('large', 'cool', 'large', 'far away', 'comfort'),
        ('large', 'cool', 'large', 'far away', 'rich'),
        ('large', 'cool', 'very large', 'near', 'empty'),
        ('large', 'cool', 'very large', 'near', 'poor'),
        ('large', 'cool', 'very large', 'near', 'average'),
        ('large', 'cool', 'very large', 'near', 'comfort'),
        ('large', 'cool', 'very large', 'near', 'rich'),
        ('large', 'cool', 'very large', 'average', 'empty'),
        ('large', 'cool', 'very large', 'average', 'poor'),
        ('large', 'cool', 'very large', 'average', 'average'),
        ('large', 'cool', 'very large', 'average', 'comfort'),
        ('large', 'cool', 'very large', 'average', 'rich'),
        ('large', 'cool', 'very large', 'far away', 'empty'),
        ('large', 'cool', 'very large', 'far away', 'poor'),
        ('large', 'cool', 'very large', 'far away', 'average'),
        ('large', 'cool', 'very large', 'far away', 'comfort'),
        ('large', 'cool', 'very large', 'far away', 'rich'),
        ('large', 'very cool', 'small', 'near', 'empty'),
        ('large', 'very cool', 'small', 'near', 'poor'),
        ('large', 'very cool', 'small', 'near', 'average'),
        ('large', 'very cool', 'small', 'near', 'comfort'),
        ('large', 'very cool', 'small', 'near', 'rich'),
        ('large', 'very cool', 'small', 'average', 'empty'),
        ('large', 'very cool', 'small', 'average', 'poor'),
        ('large', 'very cool', 'small', 'average', 'average'),
        ('large', 'very cool', 'small', 'average', 'comfort'),
        ('large', 'very cool', 'small', 'average', 'rich'),
        ('large', 'very cool', 'small', 'far away', 'empty'),
        ('large', 'very cool', 'small', 'far away', 'poor'),
        ('large', 'very cool', 'small', 'far away', 'average'),
        ('large', 'very cool', 'small', 'far away', 'comfort'),
        ('large', 'very cool', 'small', 'far away', 'rich'),
        ('large', 'very cool', 'medium', 'near', 'empty'),
        ('large', 'very cool', 'medium', 'near', 'poor'),
        ('large', 'very cool', 'medium', 'near', 'average'),
        ('large', 'very cool', 'medium', 'near', 'comfort'),
        ('large', 'very cool', 'medium', 'near', 'rich'),
        ('large', 'very cool', 'medium', 'average', 'empty'),
        ('large', 'very cool', 'medium', 'average', 'poor'),
        ('large', 'very cool', 'medium', 'average', 'average'),
        ('large', 'very cool', 'medium', 'average', 'comfort'),
        ('large', 'very cool', 'medium', 'average', 'rich'),
        ('large', 'very cool', 'medium', 'far away', 'empty'),
        ('large', 'very cool', 'medium', 'far away', 'poor'),
        ('large', 'very cool', 'medium', 'far away', 'average'),
        ('large', 'very cool', 'medium', 'far away', 'comfort'),
        ('large', 'very cool', 'medium', 'far away', 'rich'),
        ('large', 'very cool', 'large', 'near', 'empty'),
        ('large', 'very cool', 'large', 'near', 'poor'),
        ('large', 'very cool', 'large', 'near', 'average'),
        ('large', 'very cool', 'large', 'near', 'comfort'),
        ('large', 'very cool', 'large', 'near', 'rich'),
        ('large', 'very cool', 'large', 'average', 'empty'),
        ('large', 'very cool', 'large', 'average', 'poor'),
        ('large', 'very cool', 'large', 'average', 'average'),
        ('large', 'very cool', 'large', 'average', 'comfort'),
        ('large', 'very cool', 'large', 'average', 'rich'),
        ('large', 'very cool', 'large', 'far away', 'empty'),
        ('large', 'very cool', 'large', 'far away', 'poor'),
        ('large', 'very cool', 'large', 'far away', 'average'),
        ('large', 'very cool', 'large', 'far away', 'comfort'),
        ('large', 'very cool', 'large', 'far away', 'rich'),
        ('large', 'very cool', 'very large', 'near', 'empty'),
        ('large', 'very cool', 'very large', 'near', 'poor'),
        ('large', 'very cool', 'very large', 'near', 'average'),
        ('large', 'very cool', 'very large', 'near', 'comfort'),
        ('large', 'very cool', 'very large', 'near', 'rich'),
        ('large', 'very cool', 'very large', 'average', 'empty'),
        ('large', 'very cool', 'very large', 'average', 'poor'),
        ('large', 'very cool', 'very large', 'average', 'average'),
        ('large', 'very cool', 'very large', 'average', 'comfort'),
        ('large', 'very cool', 'very large', 'average', 'rich'),
        ('large', 'very cool', 'very large', 'far away', 'empty'),
        ('large', 'very cool', 'very large', 'far away', 'poor'),
        ('large', 'very cool', 'very large', 'far away', 'average'),
        ('large', 'very cool', 'very large', 'far away', 'comfort'),
        ('large', 'very cool', 'very large', 'far away', 'rich'),
        ('very large', 'average', 'small', 'near', 'empty'),
        ('very large', 'average', 'small', 'near', 'poor'),
        ('very large', 'average', 'small', 'near', 'average'),
        ('very large', 'average', 'small', 'near', 'comfort'),
        ('very large', 'average', 'small', 'near', 'rich'),
        ('very large', 'average', 'small', 'average', 'empty'),
        ('very large', 'average', 'small', 'average', 'poor'),
        ('very large', 'average', 'small', 'average', 'average'),
        ('very large', 'average', 'small', 'average', 'comfort'),
        ('very large', 'average', 'small', 'average', 'rich'),
        ('very large', 'average', 'small', 'far away', 'empty'),
        ('very large', 'average', 'small', 'far away', 'poor'),
        ('very large', 'average', 'small', 'far away', 'average'),
        ('very large', 'average', 'small', 'far away', 'comfort'),
        ('very large', 'average', 'small', 'far away', 'rich'),
        ('very large', 'average', 'medium', 'near', 'empty'),
        ('very large', 'average', 'medium', 'near', 'poor'),
        ('very large', 'average', 'medium', 'near', 'average'),
        ('very large', 'average', 'medium', 'near', 'comfort'),
        ('very large', 'average', 'medium', 'near', 'rich'),
        ('very large', 'average', 'medium', 'average', 'empty'),
        ('very large', 'average', 'medium', 'average', 'poor'),
        ('very large', 'average', 'medium', 'average', 'average'),
        ('very large', 'average', 'medium', 'average', 'comfort'),
        ('very large', 'average', 'medium', 'average', 'rich'),
        ('very large', 'average', 'medium', 'far away', 'empty'),
        ('very large', 'average', 'medium', 'far away', 'poor'),
        ('very large', 'average', 'medium', 'far away', 'average'),
        ('very large', 'average', 'medium', 'far away', 'comfort'),
        ('very large', 'average', 'medium', 'far away', 'rich'),
        ('very large', 'average', 'large', 'near', 'empty'),
        ('very large', 'average', 'large', 'near', 'poor'),
        ('very large', 'average', 'large', 'near', 'average'),
        ('very large', 'average', 'large', 'near', 'comfort'),
        ('very large', 'average', 'large', 'near', 'rich'),
        ('very large', 'average', 'large', 'average', 'empty'),
        ('very large', 'average', 'large', 'average', 'poor'),
        ('very large', 'average', 'large', 'average', 'average'),
        ('very large', 'average', 'large', 'average', 'comfort'),
        ('very large', 'average', 'large', 'average', 'rich'),
        ('very large', 'average', 'large', 'far away', 'empty'),
        ('very large', 'average', 'large', 'far away', 'poor'),
        ('very large', 'average', 'large', 'far away', 'average'),
        ('very large', 'average', 'large', 'far away', 'comfort'),
        ('very large', 'average', 'large', 'far away', 'rich'),
        ('very large', 'average', 'very large', 'near', 'empty'),
        ('very large', 'average', 'very large', 'near', 'poor'),
        ('very large', 'average', 'very large', 'near', 'average'),
        ('very large', 'average', 'very large', 'near', 'comfort'),
        ('very large', 'average', 'very large', 'near', 'rich'),
        ('very large', 'average', 'very large', 'average', 'empty'),
        ('very large', 'average', 'very large', 'average', 'poor'),
        ('very large', 'average', 'very large', 'average', 'average'),
        ('very large', 'average', 'very large', 'average', 'comfort'),
        ('very large', 'average', 'very large', 'average', 'rich'),
        ('very large', 'average', 'very large', 'far away', 'empty'),
        ('very large', 'average', 'very large', 'far away', 'poor'),
        ('very large', 'average', 'very large', 'far away', 'average'),
        ('very large', 'average', 'very large', 'far away', 'comfort'),
        ('very large', 'average', 'very large', 'far away', 'rich'),
        ('very large', 'cool', 'small', 'near', 'empty'),
        ('very large', 'cool', 'small', 'near', 'poor'),
        ('very large', 'cool', 'small', 'near', 'average'),
        ('very large', 'cool', 'small', 'near', 'comfort'),
        ('very large', 'cool', 'small', 'near', 'rich'),
        ('very large', 'cool', 'small', 'average', 'empty'),
        ('very large', 'cool', 'small', 'average', 'poor'),
        ('very large', 'cool', 'small', 'average', 'average'),
        ('very large', 'cool', 'small', 'average', 'comfort'),
        ('very large', 'cool', 'small', 'average', 'rich'),
        ('very large', 'cool', 'small', 'far away', 'empty'),
        ('very large', 'cool', 'small', 'far away', 'poor'),
        ('very large', 'cool', 'small', 'far away', 'average'),
        ('very large', 'cool', 'small', 'far away', 'comfort'),
        ('very large', 'cool', 'small', 'far away', 'rich'),
        ('very large', 'cool', 'medium', 'near', 'empty'),
        ('very large', 'cool', 'medium', 'near', 'poor'),
        ('very large', 'cool', 'medium', 'near', 'average'),
        ('very large', 'cool', 'medium', 'near', 'comfort'),
        ('very large', 'cool', 'medium', 'near', 'rich'),
        ('very large', 'cool', 'medium', 'average', 'empty'),
        ('very large', 'cool', 'medium', 'average', 'poor'),
        ('very large', 'cool', 'medium', 'average', 'average'),
        ('very large', 'cool', 'medium', 'average', 'comfort'),
        ('very large', 'cool', 'medium', 'average', 'rich'),
        ('very large', 'cool', 'medium', 'far away', 'empty'),
        ('very large', 'cool', 'medium', 'far away', 'poor'),
        ('very large', 'cool', 'medium', 'far away', 'average'),
        ('very large', 'cool', 'medium', 'far away', 'comfort'),
        ('very large', 'cool', 'medium', 'far away', 'rich'),
        ('very large', 'cool', 'large', 'near', 'empty'),
        ('very large', 'cool', 'large', 'near', 'poor'),
        ('very large', 'cool', 'large', 'near', 'average'),
        ('very large', 'cool', 'large', 'near', 'comfort'),
        ('very large', 'cool', 'large', 'near', 'rich'),
        ('very large', 'cool', 'large', 'average', 'empty'),
        ('very large', 'cool', 'large', 'average', 'poor'),
        ('very large', 'cool', 'large', 'average', 'average'),
        ('very large', 'cool', 'large', 'average', 'comfort'),
        ('very large', 'cool', 'large', 'average', 'rich'),
        ('very large', 'cool', 'large', 'far away', 'empty'),
        ('very large', 'cool', 'large', 'far away', 'poor'),
        ('very large', 'cool', 'large', 'far away', 'average'),
        ('very large', 'cool', 'large', 'far away', 'comfort'),
        ('very large', 'cool', 'large', 'far away', 'rich'),
        ('very large', 'cool', 'very large', 'near', 'empty'),
        ('very large', 'cool', 'very large', 'near', 'poor'),
        ('very large', 'cool', 'very large', 'near', 'average'),
        ('very large', 'cool', 'very large', 'near', 'comfort'),
        ('very large', 'cool', 'very large', 'near', 'rich'),
        ('very large', 'cool', 'very large', 'average', 'empty'),
        ('very large', 'cool', 'very large', 'average', 'poor'),
        ('very large', 'cool', 'very large', 'average', 'average'),
        ('very large', 'cool', 'very large', 'average', 'comfort'),
        ('very large', 'cool', 'very large', 'average', 'rich'),
        ('very large', 'cool', 'very large', 'far away', 'empty'),
        ('very large', 'cool', 'very large', 'far away', 'poor'),
        ('very large', 'cool', 'very large', 'far away', 'average'),
        ('very large', 'cool', 'very large', 'far away', 'comfort'),
        ('very large', 'cool', 'very large', 'far away', 'rich'),
        ('very large', 'very cool', 'small', 'near', 'empty'),
        ('very large', 'very cool', 'small', 'near', 'poor'),
        ('very large', 'very cool', 'small', 'near', 'average'),
        ('very large', 'very cool', 'small', 'near', 'comfort'),
        ('very large', 'very cool', 'small', 'near', 'rich'),
        ('very large', 'very cool', 'small', 'average', 'empty'),
        ('very large', 'very cool', 'small', 'average', 'poor'),
        ('very large', 'very cool', 'small', 'average', 'average'),
        ('very large', 'very cool', 'small', 'average', 'comfort'),
        ('very large', 'very cool', 'small', 'average', 'rich'),
        ('very large', 'very cool', 'small', 'far away', 'empty'),
        ('very large', 'very cool', 'small', 'far away', 'poor'),
        ('very large', 'very cool', 'small', 'far away', 'average'),
        ('very large', 'very cool', 'small', 'far away', 'comfort'),
        ('very large', 'very cool', 'small', 'far away', 'rich'),
        ('very large', 'very cool', 'medium', 'near', 'empty'),
        ('very large', 'very cool', 'medium', 'near', 'poor'),
        ('very large', 'very cool', 'medium', 'near', 'average'),
        ('very large', 'very cool', 'medium', 'near', 'comfort'),
        ('very large', 'very cool', 'medium', 'near', 'rich'),
        ('very large', 'very cool', 'medium', 'average', 'empty'),
        ('very large', 'very cool', 'medium', 'average', 'poor'),
        ('very large', 'very cool', 'medium', 'average', 'average'),
        ('very large', 'very cool', 'medium', 'average', 'comfort'),
        ('very large', 'very cool', 'medium', 'average', 'rich'),
        ('very large', 'very cool', 'medium', 'far away', 'empty'),
        ('very large', 'very cool', 'medium', 'far away', 'poor'),
        ('very large', 'very cool', 'medium', 'far away', 'average'),
        ('very large', 'very cool', 'medium', 'far away', 'comfort'),
        ('very large', 'very cool', 'medium', 'far away', 'rich'),
        ('very large', 'very cool', 'large', 'near', 'empty'),
        ('very large', 'very cool', 'large', 'near', 'poor'),
        ('very large', 'very cool', 'large', 'near', 'average'),
        ('very large', 'very cool', 'large', 'near', 'comfort'),
        ('very large', 'very cool', 'large', 'near', 'rich'),
        ('very large', 'very cool', 'large', 'average', 'empty'),
        ('very large', 'very cool', 'large', 'average', 'poor'),
        ('very large', 'very cool', 'large', 'average', 'average'),
        ('very large', 'very cool', 'large', 'average', 'comfort'),
        ('very large', 'very cool', 'large', 'average', 'rich'),
        ('very large', 'very cool', 'large', 'far away', 'empty'),
        ('very large', 'very cool', 'large', 'far away', 'poor'),
        ('very large', 'very cool', 'large', 'far away', 'average'),
        ('very large', 'very cool', 'large', 'far away', 'comfort'),
        ('very large', 'very cool', 'large', 'far away', 'rich'),
        ('very large', 'very cool', 'very large', 'near', 'empty'),
        ('very large', 'very cool', 'very large', 'near', 'poor'),
        ('very large', 'very cool', 'very large', 'near', 'average'),
        ('very large', 'very cool', 'very large', 'near', 'comfort'),
        ('very large', 'very cool', 'very large', 'near', 'rich'),
        ('very large', 'very cool', 'very large', 'average', 'empty'),
        ('very large', 'very cool', 'very large', 'average', 'poor'),
        ('very large', 'very cool', 'very large', 'average', 'average'),
        ('very large', 'very cool', 'very large', 'average', 'comfort'),
        ('very large', 'very cool', 'very large', 'average', 'rich'),
        ('very large', 'very cool', 'very large', 'far away', 'empty'),
        ('very large', 'very cool', 'very large', 'far away', 'poor'),
        ('very large', 'very cool', 'very large', 'far away', 'average'),
        ('very large', 'very cool', 'very large', 'far away', 'comfort'),
        ('very large', 'very cool', 'very large', 'far away', 'rich'),
    ]
